#!/usr/bin/env sh

{
    bspc subscribe node_swap node_transfer node_remove &
    bspc subscribe node_flag | grep --line-buffered -F "hidden off" &
    bspc subscribe node_state \
        | xargs -d "\n" -n 2 printf "%s %s\n" \
        | grep --line-buffered -vE "^node_state .* fullscreen (on|off)" &
    bspc subscribe node_add | while IFS=" " read -r _ _ _ _ i; do
        [ "$(bspc query -D -d .focused)" = "$(bspc query -D -n "$i")" ] && printf "%s\n" "$i"
    done
} | while IFS= read -r _; do
    [ -e "$XDG_CACHE_HOME/bspwm/.follows.lck" ] \
        || ! wg="$(xdotool getactivewindow getwindowgeometry)" \
        && continue
    dim="$(printf "%s\n" "$wg" | tail -n 1 | awk "{print \$NF}")"
    xdotool mousemove \
        -w "$(printf "%s\n" "$wg" | head -n 1 | awk "{print \$NF}")" \
        "$((${dim%x*} / 2))" \
        "$((${dim#*x} / 2))"
done
