#!/usr/bin/env sh

. std.sh

user="$(id -un)"
killall -u "$user" polybar
sleep 0.2
killall -9 -w -u "$user" polybar

mons="$(xrandr --listmonitors | tail -n +2 | awk '{print $NF}')"
firstmon="$(printf "%s\n" "$mons" | head -n 1)"
defsink="$(voldefsink)"
auxsink="$(volauxsink)"
config="$(getpath -uf poly)"
if [ -z "$auxsink" ] || [ "$auxsink" = "$defsink" ]; then
    sed -i 's/^\(modules-right = .*\)voldef volaux/\1voldef/' -- "$config"
else
    sed -i 's/^\(modules-right = .*\)voldef volaux/\1voldef/;s/^\(modules-right = .*voldef\)/\1 volaux/' -- "$config"
fi

DEFSINK="$defsink"
AUXSINK="$auxsink" 
POLYBAR=1
export DEFSINK
export AUXSINK
export POLYBAR

bspc monitor "$firstmon" -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
MONITOR="$firstmon" polybar --reload primary &

printf "%s\n" "$mons" | tail -n +2 | while IFS= read -r m; do
    bspc monitor "$m" -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
    MONITOR="$m" polybar --reload auxiliary &
done

wait
