#!/usr/bin/env sh
# Draw status bar.

cachedir="$XDG_CACHE_HOME"
[ -z "$cachedir" ] && cachedir="$HOME/.cache"
xsetroot -name "$( find "$cachedir/statbar" -mindepth 1 -maxdepth 1 -type f | sort -V | xargs -r cat | sed ':a;N;$!ba;s/\n/ | /g' )"
