#!/usr/bin/env sh
# Query mute status of default pulseaudio source.

stat="$( pacmd list-sources | grep -A 30 "name: <$( voldefsource )>" )"

# TODO: If the line indices are not constant, use grep.
[ "$( echo "$stat" | sed '11q;d' | awk '{print $2}' )" = "yes" ] || echo "🎤"
