#!/usr/bin/env sh
# Query battery status.

# My battery is fully charged at 94.
chargeThreshold=92

cap="$( cat /sys/class/power_supply/BAT0/capacity )"
[ "$cap" -lt "$chargeThreshold" ] && echo "$cap 🔋"
