#!/usr/bin/env sh
# Draw status bar.

xsetroot -name "$( { statbarcaps; statbarnum; statbartp; statbarkm; statbarmail; statbaravlsyu; statbarbat; statbarvol; statbardate; } | sed ':a;N;$!ba;s/\n/ \| /g' )"
