#!/usr/bin/env sh
# Query volume of default pulseaudio sink.

stat="$(pacmd list-sinks | grep -A 30 "name: <$(voldefsink)>")"

# TODO: If the line indices are not constant, use grep.
if [ "$(printf "%s" "$stat" | sed '11q;d' | awk '{print $2}')" = "yes" ]
then
    glyph="🔇"
else
    glyph="🔈"
fi

printf "%s\n" "$(printf "%s\n" "$stat" | sed '7q;d' | awk '{print $5}' | sed 's/%//') $glyph" > "$(getloc statbar)/10_statbarvol"
