#!/usr/bin/env sh
# Redraw status bar every minute.

statbarset
statbaravlsyutick &

prevDate="$( date +"%R" )"

while [ "$prevDate" = "$( date +"%R" )" ]
do
    sleep 1s
done

sleep 1s

while true
do
    statbarset &
    sleep 1m
done
