#!/usr/bin/env sh

. std.sh

[ "$BSPWMPADINIT_VERBOSE" = 1 ] && set -x

if [ "$BSPWMPADINIT_CLEAR" = 1 ]; then
    printf_term() {
        :
    }

    fillline_term() {
        :
    }
else
    printf_term() {
        printf "$@"
    }

    fillline_term() {
        fillline "$@"
    }
fi

lckdir="$1"
lck="$2"
shift 2

[ "$lck" != "0" ] && {
    printf "%s\n" "$$" > "$lckdir/$lck/pid"
    xdotool search --limit 0 --classname "bspwmpad$lck" \
        | xargs -d '\n' printf "0x%X\n" > "$lckdir/$lck/ids"
    printf_term "%s - %s\n" "bspwmpad #$lck" "$(date +"%a %F %H:%M:%S")"

    if [ "$#" -eq 0 ]; then
        printf_term "%s\n\n" "Deploying shell: $SHELL"
        fillline_term "‾"
        printf_term "\n"
        exec "$SHELL"
    else
        { printf "%s " "$@" | head -c -1; printf "\n"; } > "$lckdir/$lck/command"
        printf_term "%s\n\n" "Running command: $*"
        fillline_term "‾"
        printf_term "\n"
        exec "$@"
    fi
}

while :; do
    pid="2147483647,$(
        find "$lckdir" -mindepth 2 -maxdepth 2 -name "pid" -exec cat {} \; | tr '\n' ','
    )"
    top -n 1 -p "${pid%?}"
    tput civis
    sleep 1
done
