#!/usr/bin/env sh

. shellverbose.sh

. meta.sh

set -e

appid="$1"
shift

samrewritten -i "$appid" &
pid="$!"

trap 'kill -INT "$pid"' EXIT INT QUIT TERM

if [ "$#" -eq 0 ]; then
    wait
else
    if std_is_set "STEAM_RUNTIME"; then
        # sudo to get rid of steam runtime
        sudo -u "$USER" -- "$@"
    else
        "$@"
    fi
fi
