#!/usr/bin/env sh
# Adapted from https://www.reddit.com/r/bspwm/comments/mzlwsf/get_node_flag/gw2vne9
# Alternatively, use bspwm-qflag. It is 9.54±3.24 times as fast.

. evalverbose.sh

bspc query -T -n "${1:-"focused"}" | jq -rj '
    [
        [ "H", .hidden        ],
        [ "S", .sticky        ],
        [ "P", .private       ],
        [ "L", .locked        ],
        [ "M", .marked        ],
        [ "U", .client.urgent ]
    ]
    | map(if .[1] then .[0] else "" end)
    | add
'
