#!/usr/bin/env sh
# Query current speaker.

eval "$(evalverbose)"

{   [ "$(voldefsink)" = "alsa_output.pci-0000_00_1f.3.analog-stereo" ] && printf "📢\n"
} > "$(getpath -du -- statbar)/9_statbarspeak"
