#!/usr/bin/env sh

eval "$(evalverbose)"

{
    grep "^Exec=" "$(getpath -du -- lsa)/browser.desktop" | grep -q -- '--new-window' && printf "%s\n" "💞"
} > "$(getpath -du -- statbar)/7.5_statbarbrowser"
