#!/usr/bin/env sh
# Query mute status of default pulseaudio source.

eval "$(evalverbose)"

stat="$(pacmd list-sources | grep -A 30 "name: <$(voldefsource)>")"

# TODO: If the line indices are not constant, use grep.
{
    [ "$(printf "%s" "$stat" | sed '11q;d' | awk '{print $2}')" = "yes" ] || printf "%s\n" "🎤"
} > "$(getpath -du -- statbar)/8_statbarvolmic"
