#!/usr/bin/env sh
# Query touchpad status.

eval "$(evalverbose)"

touchpadId="$(xinput --list | grep Touch | awk '{print $6}' | sed 's/id=//')"
{
    [ "$(xinput --list-props "$touchpadId" | head -n 2 | tail -n 1 | awk '{print $4}')" = "1" ] \
        && printf "%s\n" "Touchpad"
} > "$(getpath -du -- statbar)/2_statbartp"
