#!/usr/bin/env sh
# Draw status bar.

eval "$(evalverbose)"

xsetroot -name "$(
    find "$(getpath -ds -- statbar)" -mindepth 1 -maxdepth 1 -type f \
        | sort -V \
        | xargs -d '\n' -r cat \
        | sed ':a;N;$!ba;s/\n/ | /g'
)"
