#!/usr/bin/env sh
# Set the brightness of the screen(s?). This only affects the laptop screen on my system.

dmenu -p "Enter brightness %:" < /dev/null | sed -e 's/\..*//g' -e 's/[^[:digit:]].*//g' | xargs -d '\n' -rI '{}' brightnessctl s '{}%'
