#!/usr/bin/env sh
# Decrease the brightness of screen(s?). This only affects the laptop screen on my system.

brightnessctl s "$( printf "%s\n" "$( brightnessctl g) * 100 / $( brightnessctl m ) - 5" | bc )"% > /dev/null
