#!/usr/bin/env sh
# Increase the brightness of the screen(s?). This only affects the laptop screen on my system.

brightnessctl s "$( echo "$( brightnessctl g) * 100 / $( brightnessctl m ) + 5" | bc )"% > /dev/null
