#!/usr/bin/env sh
# Connect to a previously paired bluetooth device.

bluetoothctl paired-devices | while read -r _ i devname
do
    [ "$( qdbus --system org.bluez "/org/bluez/hci0/dev_$( printf "%s" "$i" | tr ':' '_' )" org.bluez.Device1.Connected )" != "true" ] && printf "%s %s\n" "$i" "$devname"
done | sort -r | dmenu -i -p 'Which device to connect to?' | IFS= read -r dev # TODO: Do not prompt with dmenu if no entry is available.

[ -z "$dev" ] && exit 0

devname="$( printf "%s" "$dev" | awk '{$1=""; print substr($0,2)}' )"

if printf "%s" "$dev" | awk '{print $1}' | xargs -r bluetoothctl connect
then
    notify-send -t 1000 "✔ $devname" "Connected to device."
else
    notify-send -t 1000 "❌ $devname" "Could not connect to device."
fi
