#!/usr/bin/env zsh
# Disconnect from a bluetooth device. Prompts a selection if more than one device is connected.

devs="$( bluetoothctl paired-devices | awk '{print $2}' )"
cdevs=""

printf "%s" "$devs" | while read -r i
do
    [ "$( qdbus --system org.bluez "/org/bluez/hci0/dev_$( printf "%s" "$i" | sed 's/:/_/g' )" org.bluez.Device1.Connected )" = "true" ] && cdevs="$( printf "%s%s\n" "$cdevs" "$i" )"
done

# if sh is used instead of zsh, this part always exits
# find a fix and use sh
[ "$cdevs" = "" ] && {
    printf "%s\n" "No connected device, exiting."
    exit 0
}

if [ "$( printf "%s\n" "$cdevs" | wc -l )" = 1 ]
then
    ddev="$cdevs"
else
    ddev="$( printf "%s" "$cdevs" | dmenu -i -p "Device to disconnect:" )"
    [ "$ddev" = "" ] && exit 0
fi

ddevname="$( bluetoothctl info "$i" | grep -m 1 Alias: | sed 's/.*Alias:\s*//' )"

if bluetoothctl disconnect "$ddev"
then
    notify-send -t 1000 "✔  $ddevname" "Device disconnected."
else
    notify-send -t 1000 "❌ $ddevname" "Could not disconnect device."
fi

statbarset
