#!/usr/bin/env sh
# Disconnect from a bluetooth device. Prompts a selection if more than one device is connected.
# TODO: Show device names in dmenu.

cdevs="$( bluetoothctl paired-devices | while read -r _ i _
    do
        [ "$( qdbus --system org.bluez "/org/bluez/hci0/dev_$( printf "%s" "$i" | tr ':' '_' )" org.bluez.Device1.Connected )" = "true" ] && printf "%s\n" "$i"
    done
)"

[ -z "$cdevs" ] && {
    printf "No connected device, exiting.\n"
    exit 0
}

if [ "$( printf "%s\n" "$cdevs" | wc -l )" = 1 ]
then
    dev="$cdevs"
else
    dev="$( printf "%s" "$cdevs" | dmenu -i -p "Device to disconnect:" )"
    [ "$dev" = "" ] && exit 0
fi

devname="$( bluetoothctl info "$i" | grep -m 1 Alias: | sed 's/.*Alias:\s*//' )"

if bluetoothctl disconnect "$dev"
then
    notify-send -t 1000 "✔  $devname" "Device disconnected."
else
    notify-send -t 1000 "❌ $devname" "Could not disconnect device."
fi
