#!/usr/bin/env sh
# Log clipped text as a daemon (though it does not fork out). clplogynk be used to list and copy these with rofi.
# This script and clplogynk assume that the copied string does not contain the character .

fl="$( getfl clp )"
lckfl="$( getfl clplck )"
lastclp="$( xclip -o -sel clip )"
oldclp="$lastclp"

while true
do
    while clipnotify
    do
        [ -f "$lckfl" ] && {
            rm "$lckfl" && {
                oldclp="$lastclp"
                lastclp="$( xclip -o -sel clip )"
            }
            continue
        }

        clp="$( xclip -o -sel clip )"
        [ "$( printf "%s" "$clp" | sed '/^\s*$/d' )" = "" ] && continue
        if [ "$clp" != "$lastclp" ] && [ "$clp" != "$oldclp" ]
        then
            printf ": %s;\n### BEGIN CLIP ###\n%s\n### END CLIP ###\n" "$( date +%s )" "$( printf "%s\n" "$clp" | tr '\n' '' )" >> "$fl"
            lastclp="$clp"
            oldclp=""
        fi
    done
done
