#!/usr/bin/env sh
# Log clipped text as a daemon (though it does not fork out). lstynkclp can be used to list and copy these with rofi.

fl="$( getfl clp )"
lastclp="$( xclip -o -sel clip )"

while true
do
    while clipnotify
    do
        clp="$( xclip -o -sel clip )"
        [ "$( echo "$clp" | sed '/^\s*$/d' )" = "" ] && continue
        [ "$clp" = "$lastclp" ] || {
            printf ": %s;\n### BEGIN CLIP ###\n%s\n### END CLIP ###\n" "$( date +%s )" "$clp" >> "$fl"
            lastclp="$clp"
        }
    done
done
