#!/usr/bin/env sh
# Log clipped text as a daemon (though it does not fork out). clplogynk be used to list and copy these with rofi.
# This script and clplogynk assume that the copied string does not contain the character .

logfl="$( readlink -m "$( getfl clplog )" )"
bakdir="$( readlink -m "$( getloc clplogbak )" )"
lckfl="$( getfl clploglck )"
lastclp="$( xclip -o -sel clip )"
oldclp="$lastclp"

[ -f "$lckfl" ] && rm "$lckfl"

while true
do
    while clipnotify
    do
        [ -f "$lckfl" ] && {
            rm "$lckfl" && {
                oldclp="$lastclp"
                lastclp="$( xclip -o -sel clip )"
            }
            continue
        }

        clp="$( xclip -o -sel clip )"
        [ "$( printf "%s" "$clp" | sed '/^\s*$/d' )" = "" ] && continue
        if [ "$clp" != "$lastclp" ] && [ "$clp" != "$oldclp" ]
        then
            printf ": %s;\n### BEGIN CLIP ###\n%s\n### END CLIP ###\n" "$( date +%s )" "$( printf "%s\n" "$clp" | tr '\n' '' )" >> "$logfl"
            lastclp="$clp"
            oldclp=""

            [ "$( du -b "$logfl" | cut -f1 )" -gt "5242879" ] && {
                lastnum="$( find "$bakdir" -mindepth 1 -printf "%P\n" | sort -n | tail -n 1 )"
                [ -z "$lastnum" ] && lastnum="-1"
                mv "$logfl" "$bakdir/$(( lastnum + 1 ))"
                touch "$logfl"
            }
        fi
    done
done
