#!/usr/bin/env sh
# Change directory of mark.

mark="$1"
[ -z "$mark" ] && exit 1
val="$2"
mrkfl="$(getfl mrk)"

[ "$mark" != "¬" ] && {
    curval="$(grep "^$mark\s" "$mrkfl" | sed 's/^[^ ]*\s*\|\s*$//g')"
    [ "$curval" != "$val" ] && {
        printf "Current value: %s\nNew value    : %s\nOverwrite mark [%s]? (y/N)\n" "$curval" "$val" "$mark"
        equals "$(readchar)" Y y || exit 0
    }
}

gawk -i inplace -v mrkfl="$mark" -v val="$val" '$1 == mrkfl {$2=val}1' "$mrkfl"
