#!/bin/sh

# The famous "get a menu of emojis to copy" script.
#
# Taken from Luke Smith's voidrice, edited the characters path.

# Must have xclip installed to even show menu.
xclip -h 2>/dev/null || exit 1

chosen=$(cut -d ';' -f1 ${XDG_DATA_HOME:-$HOME}/code/rsrc/unicode/unicode-characters | dmenu -i -l 20 | sed "s/ .*//")

[ "$chosen" != "" ] || exit

# If you run this command with an argument, it will automatically insert the character.
if [ -n "$1" ]; then
	xdotool key Shift+Insert
else
	echo "$chosen" | tr -d '\n' | xclip -selection clipboard
	notify-send -t 700 "$chosen copied to clipboard." &
fi
