#!/usr/bin/env sh
# Run dotfilesbak-sensitive when a sensitive dot file is modified.

while true
do
    while inotifywait -e modify -r -q -q @~/.dotfiles-sensitive/.git ~/.dotfiles-sensitive
    do
        sleep 7200
        ~/.dotfiles-sensitive/dotfilesbak-sensitive
    done
done
