#!/usr/bin/env sh
# TODO: Allow force opening at a particular lock.
# TODO: If lock 0 is selected, show a dwmpad that tracks the other locks. Show current resource usage, currently running command, when the lock was acquired, etc.
# TODO: Add ability to define geometry. This would be useful for applications like spt where height is important, or with ranger where overall size is important to preview efficiently.

lckdir="$( getloc dwmpadlck )" || {
    printf "[ERROR]: getloc failed, aborting.\n"
    exit 1
}

lck="$( 
    seq 1 9 | while IFS= read -r i
    do
        mkdir "$lckdir/$i" 2> /dev/null && {
            printf "%s" "$i"
            break
        }
    done
)"

[ -z "$lck" ] && {
    notify-send -t 2000 "dwmpad" "All locks are occupied, waiting..." &

    lck="$(
        while true 
        do
            i="$( inotifywait "$lckdir" -q -e "delete" --format "%f" )"
            mkdir "$lckdir/$i" 2> /dev/null && {
                printf "%s" "$i"
                break
            }
        done
    )"
}

st -n "dwmpad$lck" -t "dwmpad #$lck" -e dwmpadinit "$lckdir" "$lck" "$@"
rm -rf "${lckdir:?}/${lck:?}"
