#!/usr/bin/env sh

lckdir="$1"
lck="$2"
shift 2

[ "$lck" != "0" ] && {
    printf "%s\n" "$$" > "$lckdir/$lck/pid"
    printf "%s - %s\n" "dwmpad #$lck" "$( date +"%a %F %R" )"

    if [ "$#" -eq 0 ]
    then
        exec "$SHELL"
    else
        { printf "%s " "$@" | head -c -1; printf "\n"; } > "$lckdir/$lck/command"
        exec "$@"
    fi
}

pids="$( find "$lckdir" -mindepth 2 -maxdepth 2 -name "pid" -exec cat {} \; | tr '\n' ',' | sed 's/,$//' )"

[ -z "$pids" ] && {
    printf "No pads to show. Press enter to exit.\n"
    readstr
    exit 0
}

exec top -p "$pids"
