#!/usr/bin/env sh
# Edit given links.

tmp="$( mktemp )"

for i
do
    if [ -L "$i" ]
    then
        printf "%s\n\nPath of symlink is: %s" "$( readlink "$i" )" "$i" > "$tmp"
        "$EDITOR" "$tmp"
        ln -sf "$( head -n 1 "$tmp" )" "$i"
    elif [ ! -e "$i" ]
    then
        printf "\n\nPath of symlinks is: %s" "$i" > "$tmp"
        "$EDITOR" "$tmp"
        ln -sf "$( head -n 1 "$tmp" )" "$i"
    else
        printf "%s exists, overwrite? (y/N): " "$i"
        read -r ans

        [ "$ans" != "${ans#[Yy]}" ] && {
            printf "\n\nPath of symlinks is: %s" "$i" > "$tmp"
            "$EDITOR" "$tmp"
            ln -sf "$( head -n 1 "$tmp" )" "$i"
        }
    fi
done
