#!/usr/bin/env sh
# Expand ~.

expandpath() {
    [ "${1%"${1#?}"}" != "~" ] && {
        printf "%s\n" "$1"
        return 0
    }

    path="$( printf "%s\n" "$1" | sed 's|/\+|/|g' )"
    [ "${path#"${path%?}"}" = "/" ] && path="${path%?}"

    [ "$path" = "~" ] && {
        printf "%s\n" "$HOME"
        return 0
    }

    case "$path"
    in
        "~/"* ) printf "%s\n" "$HOME${path#?}";;
        *     ) printf "%s\n" "$path" | ( IFS=/ read -r home rest
            user="${home#?}"
            if [ "$user" = "root" ]
            then
                if [ -z "$rest" ]
                then
                    printf "/root\n"
                else
                    printf "/root/%s\n" "$rest"
                fi
            elif id "$user" > /dev/null 2>&1
            then
                if [ -z "$rest" ]
                then
                    printf "/home/%s\n" "$user"
                else
                    printf "/home/%s/%s\n" "$user" "$rest"
                fi
            else
                printf "%s/%s\n" "$home" "$rest"
            fi );;
    esac
}

if [ -n "$1" ]
then
    for i
    do
        expandpath "$i"
    done
else
    [ -t 0 ] || {
        while read -r i 
        do
            expandpath "$i"
        done < "${@:-/dev/stdin}"
    }
fi
