#!/usr/bin/env bash
# Select a file using fzf and open it using xph-open.

main() {
    file="$( fzf )"
    [ $? -ne 0 ] && exit $?
    [ -n "$file" ] && xph-open "$file"
}

if [ "$#" -eq 0 ]
then
    while true
    do
        main
    done
else
    while true
    do
        for i
        do
            loc="$( getloc "$i" )"
            [ -d "$loc" ] && cd "$loc" && main
        done
    done
fi
