#!/usr/bin/env sh

[ "$#" -lt 2 ] && exit 1
message="$1"
shift

fls="$(printf "%s\n" "$@" | xargs -d '\n' -rn 1 realpath "--relative-to=$(git rev-parse --show-toplevel)" --)"

if [ "$#" -eq 1 ]; then
    git add -- "$1" && git commit -m "$message $fls"
else
    git add -- "$@" && git commit -m "$message $(printf "%s\n" "$fls" | sed 's/$/, /' | sort | tr -d '\n' | sed 's/, \([^ ]*\), $/ and \1/')"
fi
