#!/usr/bin/env sh

[ "$#" -lt 2 ] && exit 1
message="$1"
shift
if [ "$#" -eq 1 ]
then
    git add "$1" && git commit -m "$message $1"
else
    git add "$@" && git commit -m "$message $( printf "%s, \n" "$@" | sort | tr -d '\n' | sed 's/, \([^ ]*\), $/ and \1/' )"
fi
