#!/usr/bin/env sh

fls="$HOME/documents/sys-admin/files"

if [ $# -eq 0 ]
then
    exit
fi

for i in "$@"
do
    [ "$i" = "*" ] && {
        awk '{print $2}' "$fls"
        exit
    }
done

for i in "$@"
do
    expandpath "$( printf "%s\n" "$( grep -E "^$i\s+.*" "$fls" | awk '{print $2}' )" )"
done
