#!/usr/bin/env sh
# Get the directories of files with given codes.
# TODO: Add ordering by usage to match faster.

fls="$HOME/documents/sys-admin/files"

if [ "$#" -eq 0 ]
then
    exit 0
fi

for i
do
    [ "$i" = "*" ] && {
        awk '{print $2}' "$fls"
        exit 0
    }
done

for i
do
    dirname "$(expandpath "$(printf "%s\n" "$(grep -E "^$i\s+.*" -- "$fls" | awk '{print $2}')")")"
done
