#!/usr/bin/env sh
# Get a directory with a code.
# TODO: Add ordering by usage to match faster.

loc="$HOME/documents/sys-admin/locations"

if [ $# -eq 0 ]
then
    exit 0
fi

for i
do
    [ "$i" = "*" ] && {
        awk '{print $2}' "$loc"
        exit 0
    }
done

for i
do
    expandpath "$( printf "%s\n" "$( grep -E "^$i\s+.*" "$loc" | awk '{print $2}' )" )"
done
