#!/usr/bin/env sh
# Get directories with given codes.

set -e
item="$HOME/documents/sys-admin/locations-container/$1"
[ -s "$item" ]
loc="$( cat "$item" )"
[ -d "$loc" ] || mkdir -p "$loc"
printf "%s\n" "$loc"
