#!/usr/bin/env sh
# Get directories or the directories of files with given codes.
# TODO: Add ordering by usage to match faster.

locfl="$HOME/documents/sys-admin/locations"
flsfl="$HOME/documents/sys-admin/files"

if [ $# -eq 0 ]
then
    exit 0
fi

for i
do
    [ "$i" = "*" ] && {
        awk '{print $2}' "$loc"
        exit 0
    }
done

for i
do
    loc="$(printf "%s\n" "$(grep -E "^$i\s+.*" "$locfl" | awk '{print $2}')")"
    [ -n "$loc" ] || {
        loc="$(printf "%s\n" "$(grep -E "^$i\s+.*" "$flsfl" | awk '{print $2}')")"
        [ -n "$loc" ] && loc="$(dirname "$loc")/"
    }
    expandpath "$loc"
done
