#!/usr/bin/env sh

loc="$HOME/documents/sys-admin/locations"

if [ $# -eq 0 ]
then
    exit
fi

for i in "$@"
do
    [ "$i" = "*" ] && {
        awk '{print $2}' "$loc"
        exit
    }
done

for i in "$@"
do
    expandpath "$( printf "%s\n" "$( grep -E "^$i\s+.*" "$loc" | awk '{print $2}' )" )"
done
