#!/usr/bin/env sh

for i in "$@"
do
    [ "$i" = "-d" ] || [ "$i" = "--detect" ] && detect="1"
done

if [ "$detect" = "1" ]
then
    app="$( detectmpris )"
else
    app="$1"
fi

case "$app"
in
    spotify) lst="$( catfl spuri )";;
    *) exit 1
esac

[ "$lst" ] || exit

name="$( printf "%s" "$lst" | awk -F '' '{print $2}' | dmenu -i -l 20 -p "Select playlist:" )"
printf "%s" "$lst" | grep "$name$" | head -n 1 | awk -F '' '{print $1}'
