#!/usr/bin/env sh
# Pipe stdin to stdout if present and non-empty, else evaluate the given arguments and output its stdout.

if [ ! -t 0 ]
then
    stdinfl="$(mktemp)"
    cp -f -- /dev/stdin "$stdinfl"
fi

if [ -s "$stdinfl" ]
then
    cat -- "$stdinfl"
else
    eval "$@"
fi
