#!/usr/bin/env sh
# Toggle X keymap.

currentKeymap="$( xkb-switch )"
hasCycled="true"

case "$currentKeymap"
in
    gb) setxkbmap tr && setxkb;;
    tr) setxkbmap gb && setxkb -s;;
    *) hasCycled="false";;
esac

if "$hasCycled"
then
    notify-send -t 500 "⌨ $( xkb-switch )" "Changed current keymap"
    statbarset
else
    notify-send -t 1000 "❌ $currentKeymap" "Current keymap unknown"
fi
