#!/usr/bin/env sh
# Toggle X keymap.

setkm() {
    setxkbmap "$1"
    setxkb "$1"
    km="$1"
}

km="$( xkb-switch )"
hasCycled="true"

case "$km"
in
    gb) setkm tr;;
    tr) setkm gb;;
    *) hasCycled="false";;
esac

lcknotiflog

if "$hasCycled"
then
    notify-send -t 500 "⌨ $km" "Changed current keymap"
    statbarset
else
    notify-send -t 1000 "❌ $km" "Current keymap unknown"
fi
