#!/usr/bin/env sh
# Compile and show its PDF of a TeX file, then compile it every time it is accessed/modified/etc.
# Compilation on access is intended behaviour.
# This was written as a more robust alternative to latexmk as it seemed to fail and/or get stuck quite a lot.
# TODO: Make argument parsing more convenient.

clean() {
    cleanaux
    rm "$fl.pdf" > /dev/null 2>&1
}

cleanaux() {
    rm "$fl.aux" "$fl.bbl" "$fl.blg" "$fl.lof" "$fl.log" "$fl.lot" "$fl.out" "$fl.toc" "$fl.bcf" "$fl.run.xml" "$fl.py" "$fl.py.err" "$fl.py.out" "latex.py" > /dev/null 2>&1
}

compile() {
    # Adapted from https://tex.stackexchange.com/a/8792/199300
    xelatex -draftmode -shell-escape -halt-on-error "$fl" || {
        clean
        xelatex -draftmode -shell-escape -halt-on-error "$fl"
    }
    bibtex "$fl"
    biber "$fl"
    makeindex "$fl".idx
    # makeindex -s style.gls ...
    xelatex -draftmode -shell-escape -halt-on-error "$fl"
    xelatex -shell-escape -halt-on-error "$fl"
}

if [ "$1" = "" ]
then
    fl="main"
    printf "%s\n" "No file name given, assuming main."
else
    fl="$( printf "%s" "$1" | sed 's/\.tex$//' )"
fi

[ -f "$fl.tex" ] || {
    printf "%s\n" "No such file exists."
    exit 0
}

clean
compile

for i
do
    if [ "$i" = "-o" ] || [ "$i" = "--once" ]
    then
        cleanaux
        exit 0
    fi
done

pss="$( ps aux )"
printf "%s" "$pss" | grep -q "zathura $fl.pdf" || zathura "$fl.pdf" &

while true
do
    inotifywait -e move_self "$fl.tex"
    while [ ! -f "$fl.tex" ]; do sleep 0.1s; done
    compile
    while [ ! -f "$fl.tex" ]; do sleep 0.1s; done
done
