#!/usr/bin/env sh

lckfl="$( getfl notifloglck )" || {
    printf "[ERROR]: getfl failed, aborting.\n"
    exit 1
}

[ -f "$lckfl" ] && {
    while true
    do
        sleep 0.1
        [ -f "$lckfl" ] || break
    done

    sleep 0.1
}

touch "$lckfl"
