#!/usr/bin/env sh

if [ -z "$1" ]
then
    man bash | less +/^SHELL\ BUILTIN\ COMMANDS$
elif [ -z "$2" ]
then
    man bash | less +/^SHELL\ BUILTIN\ COMMANDS$''/"^       $1"''/"$1"
else
    printf "Only one argument is accepted.\n"
fi
