#!/usr/bin/env sh
# Adapted from https://superuser.com/a/992924/1157070.

eval "$( xdotool getwindowfocus getwindowgeometry --shell )"

while read -r mn mw mh mx my
do
    if [ "$X" -ge "$mx" ] && [ "$Y" -ge "$my" ] && [ "$X" -lt "$(( mx + mw ))" ] && [ "$Y" -lt "$(( my + mh ))" ]
    then
        hasmn="1"
        break
    fi
done <<EOF
$( xrandr | grep -w connected | sed -r "s/^([^ ]*).*\b([-0-9]+)x([-0-9]+)\+([-0-9]+)\+([-0-9]+).*$/\1 \2 \3 \4 \5/" | sort -nk4,5 )
EOF

[ "$hasmn" != 1 ] && {
    printf "Couldn't find any monitor for the current window.\n" >&2
    exit 1
}

printf "%s\n" "$mn"
