#!/usr/bin/env sh

[ "$UID" != 0 ] && {
    printf "This script needs to be executed as root.\n"
    exit 1
}

devs="$( lsblk -rpo "name,label,mountpoint" )"

while read -r i
do
    label="$( printf "%s" "$i" | awk -F '' '{print $1}' )"
    mp="$( printf "%s" "$i" | awk -F '' '{print $2}' )"

    printf "%s" "$devs" | while read -r j
    do
        devname="$( printf "%s" "$j" | awk '{print $1}' )"
        devlabel="$( printf "$( printf "%s" "$j" | awk '{print $2}' )" )"
        devmp="$( printf "%s" "$j" | awk '{print $3}' )"

        [ "$devlabel" = "$label" ] && [ -z "$devmp" ] && mount "$devname" "$mp" > /dev/null
    done
done < "$( getfl mounts )"

exit 0 # to not make systemd freak out
