#!/usr/bin/env sh

t="5s"

[ -z "$1" ] || {
    while ! ping -c 1 "$1"
    do
        sleep "$t"
    done

    [ -z "$2" ] || {
        while ! ping -c 1 "$2"
        do
            sleep "$t"
        done

        [ -z "$3" ] || {
            while ! ping -c 1 "$3"
            do
                sleep "$t"
            done
        }
    }
}

# notify-send -t 10000 "🌐 Network connected" "Connected to the specified addresses."
kdialog --msgbox "notifping\nConnected to the specified addresses."
