#!/usr/bin/env sh
# Log notifications.

# TODO: Add support for multi-line title/description of notifications.

fl="$( getfl notiflog )" || {
    printf "[ERROR]: getfl failed, aborting.\n"
    exit 1
}
lckfl="$( getfl notifloglck )" || {
    printf "[ERROR]: getfl failed, aborting.\n"
    exit 1
}
beg="##beg##"
end="##end##"

title=""
desc=""
a=0
maxa=1

rm "$lckfl"

dbus-monitor "interface='org.freedesktop.Notifications', member='Notify'" | while read -r i
do
    arr="$( printf "%s" "$i" | grep "^\s*array \[$" )"
    [ -z "$arr" ] || {
        [ "$a" = "0" ] && {
            a="$maxa"

            [ -f "$lckfl" ] && {
                rm "$lckfl"
                continue
            }

            printf "%s\n%s\n%s\n%s\n%s\n" \
                "$beg" \
                "$( date +%s )" \
                "$title" \
                "$desc" \
                "$end" >> "$fl"

            continue
        }

        a=$(( a - 1))
        continue
    }

    title="$desc"
    desc="$( printf "%s" "$i" | grep "^\s*string \".*\"$" | sed -e 's/\s*string "//' -e 's/"$//' )"
done
