#!/usr/bin/env sh
# xph-open assignments.

loc="$(getloc ass)" || {
    printf "[ERROR]: getloc failed, aborting.\n"
    exit 1
}
find -L "$loc" -mindepth 1 -type f -printf "%T@;%p\n" | sort -nr | sed 's/^[0-9]*\.[0-9]*;//' | while IFS= read -r i
do
    xph-open "$i" &
    sleep 0.1
done
