#!/usr/bin/env sh
# Open an executable file.

# TODO: Make this use where instead of type, reducing an awk.
# TODO: This does not work for multiple inputs, fix.

paths="$( type "$@" 2>/dev/null | awk '{print $3}' )"

if [ ! -z "$paths" ] 
then
    eval "'$EDITOR' '$paths'"
else
    printf "%s\n" "No such executable$( [ "$2" ] && printf "%s" "s" ) named { $( printf "%s" "$@" | sed 's/ /, /g' ) }."
fi
