#!/usr/bin/env sh
# Overwrite a file.

cp "$@" || {
    echo "Could not overwrite:" "$@"
    exit 1
}

paths="$( echo "$@" | sed 's/\s.*$//' )"

rm "$paths" || {
    echo "Could not remove:" "$paths"
    exit 1
}
