#!/usr/bin/env sh

pacmd load-module module-remap-sink master="$( voldefsink )" sink_name=mono sink_properties="device.description='Mono'" channels=2 channel_map=mono,mono
pacmd set-default-sink mono
