#!/usr/bin/env sh

compile() {
    # Adapted from https://tex.stackexchange.com/a/8792/199300
    pdflatex -draftmode -halt-on-error "$fl"
    bibtex "$fl"
    makeindex "$fl".idx
    # makeindex -s style.gls ...
    pdflatex -draftmode -halt-on-error "$fl"
    pdflatex -halt-on-error "$fl"
}

if [ "$1" = "" ]
then
    fl="main"
    echo "No file name given, assuming main."
else
    fl="$1"
fi


[ -f "$fl.tex" ] || {
    echo "No such file exists."
    exit
}

compile

zathura "$fl.pdf" &

while true
do
    while inotifywait "$fl.tex"
    do
        while [ ! -f "main.tex" ]; do sleep 0.1s; done

        compile

        while [ ! -f "main.tex" ]; do sleep 0.1s; done
    done
done
