#!/usr/bin/env sh
# Compile and show its PDF of a TeX file, then compile it every time it is accessed/modified/etc.
# Compilation on access is wanted behaviour.
# This was written as a more robust alternative to latexmk as it seemed to fail and/or get stuck quite a lot.
# TODO: Make argument parsing more convenient.
# TODO: Add option to use pdflatex, xelatex and lualatex.
# TODO: Make default xelatex of lualatex.

clean() {
    rm "$fl.aux" "$fl.bbl" "$fl.blg" "$fl.lof" "$fl.log" "$fl.lot" "$fl.out" "$fl.pdf" "$fl.toc" "$fl.py" "$fl.py.err" "$fl.py.out" "latex.py"
}

compile() {
    # Adapted from https://tex.stackexchange.com/a/8792/199300
    pdflatex -draftmode -shell-escape -halt-on-error "$fl" || {
        clean
        pdflatex -draftmode -shell-escape -halt-on-error "$fl"
    }
    bibtex "$fl"
    biber "$fl"
    makeindex "$fl".idx
    # makeindex -s style.gls ...
    pdflatex -draftmode -shell-escape -halt-on-error "$fl"
    pdflatex -shell-escape -halt-on-error "$fl"
}

if [ "$1" = "" ]
then
    fl="main"
    printf "%s\n" "No file name given, assuming main."
else
    fl="$( printf "%s" "$1" | sed 's/\.tex$//' )"
fi

[ -f "$fl.tex" ] || {
    printf "%s\n" "No such file exists."
    exit
}

clean
compile

for i
do
    if [ "$i" = "-o" ] || [ "$i" = "--once" ]
    then
        exit
    fi
done

pss="$( ps aux )"
[ "$( printf "%s" "$pss" | grep "zathura $fl.pdf" | grep -v "grep.*zathura $fl.pdf" )" = "" ] && zathura "$fl.pdf" &
# [ "$( printf "%s" "$pss" | grep "pdflatexstp "$@"" | grep -v "grep.*pdflatexstp "$@"" )" = "" ] && exit

while true
do
    inotifywait "$fl.tex"

    while [ ! -f "$fl.tex" ]; do sleep 0.1s; done

    # clean # not to allow permanent halting of compilation in the case of corrupted files
    compile

    while [ ! -f "$fl.tex" ]; do sleep 0.1s; done
done
