#!/usr/bin/env sh
# Pings specified addresses and notifies the user when all succeeded once.

t="5s"

[ -z "$1" ] || {
    while ! ping -c 1 "$1"
    do
        sleep "$t"
    done

    [ -z "$2" ] || {
        while ! ping -c 1 "$2"
        do
            sleep "$t"
        done

        [ -z "$3" ] || {
            while ! ping -c 1 "$3"
            do
                sleep "$t"
            done
        }
    }
}

notify-send -u critical -t 0 "🌐 pingnotif" "Connected to the specified addresses on $( date )."
