#!/usr/bin/env sh
# Generate random things.
# DO NOT USE THIS IN SENSITIVE APPLICATIONS.

cmd="$1"
shift

case "$cmd"
in
    char)
        for i
        do
            strings /dev/urandom | tr -d '\n\0' | head -c "$i"
            printf "\n"
        done
        ;;
    byte)
        for i
        do
            head -c "$i" /dev/urandom
        done
        ;;
    safebyte)
        for i
        do
            tr -d '\0' < /dev/urandom | head -c "$i"
        done
        ;;
    int)
        cprintf "%d" "$( random safebyte 4 )"
        printf "\n"
        ;;
    long)
        cprintf "%ld" "$( random safebyte 8 )"
        printf "\n"
        ;;
esac
