#!/usr/bin/env zsh

case "$1"
in
    one) name="onedrive";;
    open) name="opendrive";;
    *) exit;;
esac

[ -d ~/"$name" ] || mkdir ~/"$name"
sudo rclone --vfs-cache-mode writes mount "$1": ~/"$name" & disown
