#!/usr/bin/env zsh
# Mount a remote drive with rclone based on the given drive code.

case "$1"
in
    one) name="onedrive";;
    open) name="opendrive";;
    *) echo "No drive code given, exiting."; exit;;
esac

[ -d ~/"$name" ] || mkdir ~/"$name"
sudo rclone mount --daemon --allow-other --vfs-cache-mode writes "$1": ~/"$name" & disown
