#!/usr/bin/env sh

case "$1"
in
    one) name="onedrive";;
    open) name="opendrive";;
    *) echo "No drive code given, exiting."; exit;;

esac

sudo mkdir "$name"sync
sudo rclone sync -L ~/"$name"sync "$1":linux/arch
