#!/usr/bin/env sh
# Adapted from https://stackoverflow.com/a/30022297/8403070.

readchar() {
  stty -icanon -echo
  eval "$1=\$( dd bs=1 count=1 2> /dev/null )"
  stty icanon echo
}

readchar char
# shellcheck disable=SC2154
printf "%s" "$char"
