#!/usr/bin/env sh
# Resolve recursive symlinks into a direct symlink.

# TODO: This resolves direct recursive symlinks, but does not resolve inner recursive symlinks, add an option to also fix them.
# Example: a/, a/b, b->a, c->b/b => This script does not fix c to point to a/b as b is not a symlink itself (although it is reached from a symlink).
# TODO: Fix problems with directories (test on "$(getloc off )" to see the problem (i.e. the input is "$( getloc off)"/*))
# TODO: The resolved symlink may become broken if a symlink is relative at any point in the chain, fix.
# TODO: If the first symlink was relative, leave the resolved symlink relative.

log() {
    printf "[resln]: %s\n" "$1"
}

for i
do
    [ -L "$i" ] || {
        log "\"$i\" does not exist or is not a symlink, ignoring."
        continue
    }

    idest="$(readlink -- "$i")"
    dest="$idest"
    while [ -L "$dest" ]
    do
        dest="$(readlink -- "$dest")"
    done

    ln -sf -- "$dest" "$i"
    log "Resolved $i from $idest to $dest."
done
