#!/usr/bin/env sh
# Resolve recursive symlinks into a direct symlink.

# TODO: If the symlink was relative, leave the resolved symlink relative.

log() {
    printf "[resln]: %s\n" "$1"
}

for i; do
    [ -L "$i" ] || {
        log "\"$i\" does not exist or is not a symlink, ignoring."
        continue
    }

    ln -vsf -- "$(realpath -P -- "$i")" "$i"
done
