#!/usr/bin/env bash
# Restart dotfilesbaktick and dotfilesbaktick-sensitive.

# shellcheck disable=SC2009
for i in $( ps aux | grep -E "(sh|inotifywait)\s.*\.?dotfiles(-sensitive)?(baktick)?(-sensitive)?" | grep -vE "grep\s.*-E" | awk '{print $2}' )
do
    kill "$i"
done

dotfilesbaktick &
dotfilesbaktick-sensitive &
disown
