#!/usr/bin/env sh

dir="$HOME/documents/notes/scratchpad"

files="$( find "$dir" -type f -printf "%f\n" | sort -rV )"
newfile="$( echo "$files" | head -n 1 | sed 's/_.*//' )"
[ "$newfile" = "" ] && newfile=-1

: $(( newfile += 1 ))
newfile="$newfile"_"$( date +"%Y-%m-%d_%H-%M-%S" )"

file="$( printf "%s\n%s" "$newfile" "$files" | dmenu -i )"

[ "$file" ] || exit

[ "$file" = "$newfile" ] && isnew=1

if [ "$isnew" = "1" ]
then
    vimcmd='startinsert'
else
    vimcmd='norm G$'
fi

path="$dir/$file"

vim "$path" -c "$vimcmd"

while true
do
    [ "$isnew" = "1" ] && {
        [ -f "$path" ] && title="$( echo "" | dmenu -p "Title for \"$path\":" )"
        # currently seconds are included in the title, so no duplicates should occur, but just in case we change this behaviour, we will check for file clashes:
        [ "$title" -a ! -f "$path\_$title" ] && {
            mv "$path" "$path\_$title"
            break
        }
    }
done

