#!/usr/bin/env sh

dir="$HOME/documents/notes/scratchpad"

files="$( find "$dir" -type f -printf "%f\n" )"
newfile="$( echo "$files" | sort -V | tail -n 1 | sed 's/_.*//' )"
[ "$newfile" = "" ] && newfile=-1

: $(( newfile += 1 ))
newfile="$newfile"_"$( date +"%Y-%m-%d_%H-%M-%S" )"

file="$( printf "%s\n%s" "$newfile" "$files" | dmenu -i )"

if [ "$file" = "$newfile" ]
then
    vim "$dir/$file" -c 'startinsert'
else
    vim "$dir/$file" -c 'norm G$'
fi
