#!/usr/bin/env sh
# Take and manage notes with dmenu.
# Designed to work as a scratchpad to dwm with st.

dir="$HOME/documents/notes/scratchpad"

files="$( find "$dir" -type f -printf "%f\n" | sort -rV )"
newfile="$( printf "%s" "$files" | head -n 1 | sed 's/_.*//' )"
[ "$newfile" = "" ] && newfile=-1

: $(( newfile += 1 ))
newfile="$newfile"_"$( date +"%Y-%m-%d_%H-%M-%S" )"

file="$( printf "%s\n%s" "$newfile" "$files" | dmenu -i )"

[ "$file" ] || exit

if ! [ "$file" = "$newfile" ] && ! printf "%s" "$files" | grep -Fxq "$file"
then
    printf "%s" "$file" > "$dir/${newfile}_$( printf "%s\n" "" | dmenu -p "Title for \"$dir/$newfile\":" )"
    exit
fi

[ "$file" = "$newfile" ] && isnew=1

if [ "$isnew" = "1" ]
then
    vimcmd='startinsert'
else
    vimcmd='norm G$'
fi

path="$dir/$file"

vim "$path" -c "$vimcmd"

[ "$isnew" = "1" ] && {
    [ -f "$path" ] && title="$( printf "%s\n" "" | dmenu -p "Title for \"$path\":" )"
    [ "$title" ] && mv "$path" "${path}_$title"
}
