#!/usr/bin/env sh

se="$(dmenu -F -i -l 20 -p "search engine:" < "$(getfl search)" | awk -F, '{print $NF}')"
[ -n "$se" ] && printf "%s\n" "$se" | sed "s/%s/$(dmenu -l 0 -p "search term:" < /dev/null | tr -d '\n' | jq -sRr @uri)/g" | xargs -rn 1 xdg-open
