#!/usr/bin/env sh
# Select a file or a directory using dmenu.
# TODO: Make -d respect -g.

printhelp() {
    echo "selfl [OPTION...] [DIRECTORY...]"
    echo "   -a, --absolute"
    echo "       Prints absolute path instead of relative."
    echo "   -d, --directory"
    echo "       Only shows directories. If selecting a directory, you must exit without selecting after navigating to the wanted directory."
    echo "   -g, --git"
    echo "       Use git ls-files to list files. Does nothing if -d is given."
    echo "   -H, --with-directory"
    echo "       Print initial directory with the selections."
    echo "   -h, --help"
    echo "       Print help message."
    echo "   -s, --show-hidden"
    echo "       Shows hidden directories/files."
}

printusage() {
    printf "Option [$1] is not valid.\n\n"
    printhelp
}

cdsafe() {
    cd "$1" 2> /dev/null || {
        echo "ERROR: Could not cd to $1, exiting."
        exit
    }
}

parseargs() {
    for i
    do
        if [ "${i%"${i#?}"}" = "-" ]
        then
            if ! [ "${i%"${i#??}"}" = "--" ]
            then
                sopt="$( printf "%s" "$i" | cut -c2- )"

                while [ "$sopt" ]
                do
                    opt="$( printf "%s" "$sopt" | cut -c1 )"

                    case "$opt" in
                        a) absolute="1";;
                        d) directory="1";;
                        g) git="1";;
                        h) printhelp; exit;;
                        H) printinitpwd="1";;
                        s) showhidden="1";;
                        *) printusage "-$opt"; exit;;
                    esac

                    sopt="$( printf "%s" "$sopt" | cut -c2- )"
                done
            else
                opt="$( printf "%s" "$i" | cut -c3- )"
                
                case "$opt" in
                    absolute       ) absolute="1";;
                    directory      ) directory="1";;
                    git            ) git="1";;
                    help           ) printhelp; exit;;
                    with-directory ) printinitpwd="1";;
                    show-hidden    ) showhidden="1";;
                    *              ) printusage "--$opt"; exit;;
                esac
            fi
        else
            initdirs="$initdirs$i
"
        fi
    done
}

main() {
    if ! [ "$directory" ]
    then
        [ "$git" ] && initgithash="$( git rev-parse HEAD )"

        until [ -e "$sel" ] && [ ! -d "$sel" ]
        do
            [ -d "$sel" ] && cdsafe "$sel"

            if [ "$showhidden" ]
            then
                if [ "$git" ]
                then
                    [ "$( git rev-parse --is-inside-work-tree 2> /dev/null )" = "true" ] || {
                        echo "ERROR: Not a git repository, exiting."
                        exit
                    }

                    fls="$( 
                        find . -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | while read -r i
                        do 
                            cdsafe "$i"

                            if [ "$( git rev-parse --is-inside-work-tree 2> /dev/null )" = "true" ] && [ "$( git rev-parse HEAD )" = "$initgithash" ]
                            then
                                printf "%s\n" "$i"
                            fi

                            cdsafe ..
                        done | sort

                        git ls-files
                    )"
                else
                    fls="$( find . -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | sort; find . -mindepth 1 -maxdepth 1 -type f -printf "%P\n" | sort )"
                fi
            else
                if [ "$git" ]
                then
                    [ "$( git rev-parse --is-inside-work-tree 2> /dev/null )" = "true" ] || {
                        echo "ERROR: Not a git repository, exiting."
                        exit
                    }

                    fls="$( 
                        find . -mindepth 1 -maxdepth 1 -type d -not -name ".*" -printf "%P\n" | while read -r i
                        do 
                            cdsafe "$i"

                            if [ "$( git rev-parse --is-inside-work-tree 2> /dev/null )" = "true" ] && [ "$( git rev-parse HEAD )" = "$initgithash" ]
                            then
                                printf "%s\n" "$i"
                            fi

                            cdsafe ..
                        done | sort

                        git ls-files | sed -e '/^\..*/d' -e '/.*\/\..*/d'
                    )"
                else
                    fls="$( find . -mindepth 1 -maxdepth 1 -type d -not -name ".*" -printf "%P\n" | sort; find . -mindepth 1 -maxdepth 1 -type f -not -name ".*" -printf "%P\n" | sort )"
                fi
            fi

            if [ "$PWD" = "/" ]
            then
                sel="$( printf "%s" "$fls"  | dmenu -i )"
            elif [ "$git" ]
            then
                if contains "$( realpath "$PWD/.." )" "$( git rev-parse --show-toplevel )"
                then
                    sel="$( printf "..\n%s" "$fls"  | dmenu -i )"
                else
                    sel="$( printf "%s" "$fls"  | dmenu -i )"
                fi
            else
                sel="$( printf "..\n%s" "$fls"  | dmenu -i )"
            fi

            printf "%s" "$fls" | grep -Fxq "$sel" || sel="$( expandpath "$sel" )"

            [ "$sel" ] || exit
        done

        [ "$printinitpwd" ] && printinitpwd="$initpwd: "

        if [ "$absolute" ]
        then
            printf "%s%s\n" "$printinitpwd" "$PWD/$sel"
        else
            printf "%s%s\n" "$printinitpwd" "$( realpath --relative-to="$initpwd" "$PWD/$sel" )"
        fi
    else

        while true
        do
            [ -d "$sel" ] && cdsafe "$sel"

            if [ "$showhidden" ]
            then
                fls="$( find . -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | sort )"
            else
                fls="$( find . -mindepth 1 -maxdepth 1 -type d -not -name ".*" -printf "%P\n" | sort )"
            fi

            if [ "$PWD" = "/" ]
            then
                sel="$( printf "%s" "$fls"  | dmenu -i )"
            else
                sel="$( printf "..\n%s" "$fls"  | dmenu -i )"
            fi

            printf "%s" "$fls" | grep -Fxq "$sel" || sel="$( expandpath "$sel" )"

            [ "$sel" ] || {
                [ "$printinitpwd" ] && printinitpwd="$initpwd: "

                if [ "$absolute" ]
                then
                    printf "%s%s\n" "$printinitpwd" "$PWD"
                else
                    realpath --relative-to="$initpwd" "$PWD"
                fi

                break
            }
        done
    fi
}

parseargs "$@"

if [ "$initdirs" ]
then
    printf "%s" "$initdirs" | while read -r i
    do
        cdsafe "$i"

        initpwd="$PWD" main
    done
else
    initpwd="$PWD" main
fi
