#!/usr/bin/env sh

flsfl="$HOME/documents/sys-admin/files"
sort -o "$flsfl" -- "$flsfl"
container="$flsfl-container"
rm -rf -- "$container"
mkdir -p -- "$container"

while IFS=" " read -r i j
do
    contains "$i" / && {
        printf "Keycode cannot contain /, aborting.\n"
        exit 1
    }
    
    printf "%s\n" "$j" | expandpath > "$container/$i"
done < "$flsfl"
