#!/usr/bin/env sh
# Set X keyboard properties.

setxkbmap -option "caps:escape"

xmodmap -e "keycode 9 = Caps_Lock"
xset -r 9

xset r rate 250 40

xmodmap -e "keycode 108 = Super_R"

case "$( xkb-switch )"
in
    gb) xmodmap -e "keycode 135 = Menu";;
    tr) xmodmap -e "keycode 135 = ISO_Level3_Shift";;
esac

