#!/usr/bin/env sh
# Print logged results of speedtestlog.

fl="$( getfl stl )"
pingav="0.0"
dowav="0.0"
upav="0.0"

while read -r i
do
    time="$( echo "$i" | awk -F \; '{print $1}' )"
    isp="$( echo "$i" | awk -F \; '{print $2}' )"
    server="$( echo "$i" | awk -F \; '{print $3}' )"
    ping="$( echo "$i" | awk -F \; '{print $4}' )"
    download="$( echo "$i" | awk -F \; '{print $5}' )"
    upload="$( echo "$i" | awk -F \; '{print $6}' )"

    pingav="$( echo "scale = 10; $pingav + $( echo "$ping" | awk '{print $1}' )" | bc )"
    dowav="$( echo "scale = 10; $dowav + $( echo "$download" | awk '{print $1}' )" | bc )"
    upav="$( echo "scale = 10; $upav + $( echo "$upload" | awk '{print $1}' )" | bc )"

    printf "%s\n%s\n%s\n%s\n%s\n%s\n\n" \
        "Time    : $( date --date @"$time" )" \
        "ISP     : $isp" \
        "Server  : $server" \
        "Ping    : $ping" \
        "Download: $download" \
        "Upload  : $upload"
done < "$fl"

count="$( wc -l < "$fl" )"

# assuming the inout will be in ms and Mbit/s
printf "%s\n%s\n%s\n" \
    "Ping average    : $( echo "scale = 2; $pingav / $count" | bc ) ms" \
    "Download average: $( echo "scale = 2; $dowav / $count" | bc ) Mbit/s" \
    "Upload average  : $( echo "scale = 2; $upav / $count" | bc ) Mbit/s"
