#!/usr/bin/env sh
# Use speedtest to test internet connection and log the results. speedtestlogp can be used to print the logs.

ping -c 1 speedtest.net > /dev/null 2>&1 || {
    printf "%s\n" "Cannot reach speedtest.net servers, exiting."
    exit 1
}

printf "%s\n" "Testing..."

result="$( speedtest || { 
    printf "%s\n" "Test failed, exiting."
    exit 1
} )"

log="$(date +%s );$(printf "%s" "$result" | grep "Testing from" | sed -e 's/Testing from //' -e 's/\.\.\.//' );$(echo "$result" | grep "Hosted by" | sed -e 's/Hosted by //' -e 's/:.*//');$( echo "$result" | grep "Hosted by" | awk '{print $(NF - 1)" "$NF}');$( echo "$result" | grep "Download:" | awk '{print $2" "$3}');$( echo "$result" | grep "Upload:" | awk '{print $2" "$3}')"

echo
printf "%s" "$log" | sed 's/;/\n/g'
printf "\n\nLogging results...\n"

fl="$(getfl stl)" || {
    printf "[ERROR]: getfl failed, aborting.\n"
    exit 1
}

printf "%s\n" "$log" >> "$fl"

printf "%s\n" "Done."
