#!/usr/bin/env sh

ping -c 1 speedtest.net > /dev/null 2>&1 || {
    echo "Cannot reach speedtest.net servers, exiting."
    exit 1
}

echo "Testing..."

result="$( speedtest || { 
    echo "Test failed, exiting."
    exit 1
} )"

log="$( date +%s ); $( echo "$result" | grep "Testing from" | sed -e 's/Testing from //' -e 's/\.\.\.//' ); $( echo "$result" | grep "Hosted by" | sed -e 's/Hosted by //' -e 's/:.*//' ); $( echo "$result" | grep "Hosted by" | awk '{print $(NF - 1)" "$NF}' ); $( echo "$result" | grep "Download:" | awk '{print $2" "$3}' ); $( echo "$result" | grep "Upload:" | awk '{print $2" "$3}')"

echo "$log"
echo "Logging results..."

fl="$( getfl stl )"

echo "$log" >> "$fl"

echo "Done."
