#!/usr/bin/env sh

check() {
    isdir=0
    for i in "$@"
    do
        [ -f "$i" ] || [ -d "$i" ] || { 
            echo "$i does not exist."
            exit 1 
        }
        
        [ -d "$i" ] && isdir=1
    done

    [ "$isdir" = "1" ] && {
        for i in "$@"
        do
            [ -d "$i" ] || {
                echo "Cannot swap a file and a directory."
                exit 1
            }
        done
    }
}

swap() {
    if [ "$( stat -c%s "$1" )" -lt "$( stat -c%s "$2" )" ]
    then
        tocopy="$1"
        other="$2"
    else
        tocopy="$2"
        other="$1"
    fi

    tmp="$( mktemp )"
    [ "$tmp" = "" ] && echo "Could not create tmp file."
    cp -r "$tocopy" "$tmp" || { echo "Could not copy $tocopy to $tmp."; exit 1; }
    cp -r "$other" "$tocopy" || { echo "Could not copy $other to $tocopy. (tmp: $tmp)"; exit 1; }
    cp -r "$tmp" "$other" || { echo "Could not copy $tmp to $other."; exit 1; }
    rm "$tmp" || echo "Could not remove $tmp."
}

if [ "$3" ]
then
    echo "At most two arguments are accepted."
elif [ "$2" ]
then
    check "$1" "$2"
    swap "$1" "$2"
elif [ "$1" ]
then
    check "$1" "$1"_
    swap "$1" "$1"_
else
    echo "At least one argument is needed."
fi
