#!/usr/bin/env sh
# Update packages using dmenu.

ans="$(printf "yes\n%s\nyes" "$(yay -Qu)" | dmenu -i -p "Proceed with installation?")"
[ "$ans" = "yes" ] || exit 0

if yay -Syu --noconfirm
then
    notify-send -t 1000 "✔ Syu" "Update succeeded" 
else
    notify-send -t 1000 "❌ Syu" "Update failed"
fi

statbarsetavlsyu
statbarset
