#!/usr/bin/env sh
# Like tail, but for words.

if [ "$#" = 0 ]
then
    end=3
else
    end="$( printf "%s" "$1" | sed -e 's/\..*//g' -e 's/[^[:digit:]].*//g' )"
    [ -z "$end" ] && exit 1
fi

awk -v end="$end" '{for (i = 1; i <= NF - end; i++) $i = ""; printf $0"\n"}' | sed 's/^\s*//'
