#!/usr/bin/env sh
# Toggle an application on/off (i.e. launch or kill it).
# TODO: Instead of using environmental variables, parse arguments.

if [ "$GREP" ]
then
    grp="$GREP"
else
    willgrp=1
fi

if [ "$EXEC" ]
then
    exe="$EXEC"
else
    willexe=1
fi

if [ "$KA" ]
then
    ka="$KA"
elif [ "$KC" ]
then
    kc="$KC"
else
    willka=1
fi

if [ "$willgrp" = "1" ] || [ "$willexe" = "1" ] || [ "$willka" = "1" ]
then
    if [ "$PROCESS" ]
    then
        [ "$willgrp" = "1" ] && grp="$PROCESS"
        [ "$willexe" = "1" ] && exe="$PROCESS"
        [ "$willka" = "1" ] && ka="$PROCESS"
    else
        printf "%s\n" "Not enough environment variables."
        exit 1
    fi
fi

prc="$( ps aux | grep "$grp" | grep -vE "\s+grep\s+" )"
if [ "$prc" = "" ]
then
    $exe
else
    if [ "$kc" ]
    then
        n="$kc"
        printf "%s\n" "$prc" | while read -r i
        do
            [ "$n" = "0" ] && break
            n=$(( n - 1 ))

            kill "$( printf "%s" "$i" | awk '{print $2}' )"
        done
    else
        # TODO: Make double killing into an option.
        killall "$ka"
        killall "$ka" # some apps are problematic, hence the second killall.
    fi
fi
