#!/usr/bin/env sh

failed=""
for i
do
    [ "$(mimetype -b "$i")" != "application/pdf" ] && {
        failed="$failed$i
"
        continue
    }

    tmp="$(mktemp -p /tmp "trimpdf-${i##*"/"}-XXXXXX.pdf")"

    cp -f "$i" "$tmp" || {
        failed="$failed$i
"
        continue
    }

    rm -f "$i"
    pdf-crop-margins "$tmp" -o "$i" || {
        failed="$failed$i
"
        continue
    }

    # not removing the temp file is intentional
done
