#!/usr/bin/env sh

failed=""
for i
do
    [ "$(mimetype -b -- "$i")" != "application/pdf" ] && {
        failed="$failed$i
"
        continue
    }

    tmp="$(mktemp -p /tmp "trimpdf-${i##*"/"}-XXXXXX.pdf")"

    cp -f -- "$i" "$tmp" || {
        failed="$failed$i
"
        continue
    }

    rm -f -- "$i"
    # pdf-crop-margins cannot cut perfectly on the first try
    seq 2 | while IFS= read -r _
    do
        pdf-crop-margins -o "$i" -- "$tmp" || {
            failed="$failed$i
"
            continue
        }
        pdf-crop-margins -o "$tmp" -- "$i" || {
            failed="$failed$i
"
            continue
        }
    done
    cp -f -- "$tmp" "$i"

    # not removing the temp file is intentional
done
