#!/bin/sh
# A dmenu prompt to unmount drives. Provides you with mounted partitions, select one to unmount. Drives mounted at /, /boot and /home will not be options to unmount.
# Adapted from Luke Smith's voidrice.

unmountusb() {
	[ -n "$drives" ] || exit 1

	chosen="$(printf "%s" "$drives" | dmenu -i -p "Unmount which drive?" | awk '{print $1}')"
	[ -n "$chosen" ] || exit 1

	sudo -A umount "$chosen" && notify-send "💻 Drive unmounting" "$chosen unmounted."
}

unmountandroid() {
	chosen="$(awk '/simple-mtpfs/ {print $2}' /etc/mtab | dmenu -i -p "Unmount which device?")"
	[ -n "$chosen" ] || exit 1

	sudo -A umount -l "$chosen" && notify-send "🤖 Android unmounting" "$chosen unmounted."
}

asktype() {
	case "$(printf "Drive\\nAndroid" | dmenu -i -p "Unmount a drive or Android device?")" in
		USB     ) unmountusb ;;
		Android ) unmountandroid ;;
        *       ) exit 0;;
	esac
}

drives="$(lsblk -nrpo "name,type,size,mountpoint" | awk '$2=="part"&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}')"

if ! grep simple-mtpfs /etc/mtab
then
	[ -n "$drives" ] || exit 0

	unmountusb
else
	if [ -n "$drives" ]
	then
        asktype
	else
        unmountandroid
	fi
fi
