#!/usr/bin/env bash

lckfl="$( getfl upabllck )"

[ -f "$lckfl" ] && {
    echo "Lock file is present, waiting..."

    while [ -f "$lckfl" ]
    do
        sleep 1s
    done
}

touch "$lckfl"

# yay -Syu # --noconfirm

printf "[update]: Reading updateables.\n\n"

lst="$( getfl upabl )"

while read -r i
do
    [ "${i::1}" = "#" ] && continue

    loc="$( echo "$i" | awk -F ";" '{print $1}' )"
    cmd="$( echo "$i" | awk -F ";" '{print $2}' )"

    echo "[update]: Parsing $loc."

    cd "$( getloc "$loc" )" || {
        echo "[update]: Could not find location $loc."
        continue
    }

    echo "[update]: Pulling updates."
    if [ "$( git pull | tail -n 1 | grep --color=never -o " up to date.$" )" = " up to date." ] 
    then
        echo "[update]: Already up to date."
    else
        $cmd
    fi

    echo
done < "$lst"

rm "$lckfl"

echo "[update]: Done."
