#!/usr/bin/env sh
# Find music scores in PDF format, prompt them with dmenu and open the selected one.
# TODO: After all of the documents are closed, ask whether $n was satisfactory, then save it such that it will not be asked the next time if it was satisfactory; else, ask for a new number and if given, save that instead.
# TODO: Make this into a more general helper script to open a file in a directory based on some custom filtering/sorting, and use that helper script to do what this script currently does.

dir="$(getloc mu)" || {
    printf "[ERROR]: getloc failed, aborting.\n"
    exit 1
}

fl="$(find "$dir" -mindepth 2 -regextype egrep -regex '.*/(done|in-progress|self)/.*\.pdf' -printf "%A@;%P\n" | sort -nr | cut -d ';' -f2- | dmenu -i -l 20 -p "Select sheet music:")" || exit 1

while true; do
    n="$(seq 4 | dmenu -F -p "How many to open:")" || exit 1
    printf "%s" "$n" | grep -xq "[[:digit:]]\+" && break
done

notify-send -t 2000 "view-music" "Opening $n of ${fl##*/} with $OPENER."
i=-1
while [ $((i += 1)) -lt $n ]; do
    eval "'$OPENER' '$dir/$fl'" &
done
wait
