#!/usr/bin/env sh
# Find music scores in PDF format, prompt them with dmenu and open the selected one.

dir="$( getloc mu )"

fls="$( find "$dir" -mindepth 2 -iname "*.pdf" )"

fl="$( printf "%s" "$fls" | dmenu -i -l 20 -p "Select sheet music:" )"

[ "$fl" = "" ] && exit

xdg-open "$fl"
