#!/usr/bin/env sh
# Toggle the mute status of the default pulseaudio sink.

#pulseaudio-ctl mute #&& notify-send -t 1000 "🔇 Volume Mute" "$( pulseaudio-ctl status | tail -n 5 | head -n 1 | rmclr )"
pactl set-sink-mute "$( voldefsink )" toggle
