#!/usr/bin/env sh
# Increase the volume of the default pulseaudio sink.

#pulseaudio-ctl up #&& notify-send -t 300 "🔊 Volume Up" "$( pulseaudio-ctl status | tail -n 5 | head -n 1 | rmclr )"
pactl set-sink-volume "$( voldefsink )" +5%
