#!/usr/bin/env sh

while true; do
    allexist="1"
    for i; do
        [ -e "$i" ] || {
            allexist="0"
            break
        }
    done
    [ "$allexist" = "1" ] && exit 0
    sleep 0.05
done
