#!/usr/bin/env sh

fls="$( find "$( getloc wa )" -mindepth 1 -maxdepth 1 -type f )"

[ "$1" = "1" ] && {
    shuffle="1"
    fls="$( printf "%s" "$fls" | shuf )"
    shift
}

sleep "$1"
hsetroot -cover "$( printf "%s" "$fls" | head -n 1 )"

sleep "$2"
hsetroot -cover "$( printf "%s" "$fls" | head -n 1 )"

sleep "$3"

while true
do
    printf "%s" "$fls" | while read -r i
    do
        cmp -s "$i" "$last" && continue
        hsetroot -cover "$i"
        last="$i"
        sleep "$4"
    done

    [ "$shuffle" = "1" ] && fls="$( printf "%s" "$fls" | shuf )"
done
