#!/usr/bin/env bash

starttsm() {
    WINEPREFIX=/games/wow-tsm wine '/games/wow-tsm/drive_c/Program Files (x86)/TradeSkillMaster Application/app/TSMApplication.exe' &!
}

startrio() {
    "$( getloc prog )/RaiderIO/AppRun" &!
}

startwow() {
    screen -dmS wow sh -c 'lutris lutris:rungame/world-of-warcraft'
}

startall() {
    starttsm
    startrio
    startwow
}

input="$( printf "All\nTSM\nRaiderIO\nWoW" | dmenu -i -p "wowstart:" )"

[ -z "$input" ] && exit 0

case "$input"
in
    "All"      ) startall;;
    "TSM"      ) starttsm;;
    "RaiderIO" ) startrio;;
    "WoW"      ) startwow;;
    *          ) exit 1;;
esac
