#!/usr/bin/env bash

WINEPREFIX=/games/wow-tsm wine '/games/wow-tsm/drive_c/Program Files (x86)/TradeSkillMaster Application/app/TSMApplication.exe' &!

"$( getloc prog )/RaiderIO/AppRun" &!

screen -dmS wow sh -c 'lutris lutris:rungame/world-of-warcraft'
