#!/usr/bin/env sh

xdgopen() {
    exec "$(whereis xdg-open | awk '{$1=""; print $0}' | sed "s/$(realpath "$0" | sed 's,/,\\/,g')//" | awk '{print $1}')" "$@"
}

unset XDG_CURRENT_DESKTOP

[ "$#" -eq 1 ] && logfl="$(getfl xdgopenlog)" && {
    case "$1"
    in
        --help|--manual|--version) :;;
        *)
            if [ -e "$1" ]
            then
                arg="$(realpath "$1")"
            else
                arg="$1"
            fi
            printf "%s; %s\n" "$(date +"%s")" "$arg" >> "$logfl"
            ;;
    esac
}

xdgopen "$@"
