#!/usr/bin/env sh

logfl="$( getfl xdgopenlog )" || {
    printf "[ERROR]: getfl failed, aborting.\n"
    exit 1
}

sel="$( dmenu -sel 200000000 -l 20 -p 'xdg-reopen:' < "$logfl" | ( IFS="; " read -r _ sel; printf "%s\n" "$sel" ) )"
[ -z "$sel" ] && exit 0
lckget xdgopenlog
xdg-open "$sel"
