#!/usr/bin/env sh

logfl="$( getfl xdgopenlog )" || {
    printf "[ERROR]: getfl failed, aborting.\n"
    exit 1
}
dmenu -sel 200000000 -l 20 -p 'xdg-reopen:' < "$logfl" | awk -F '' '{print $2}' | xargs -r xdg-open
