#!/usr/bin/env sh

xr="$( xrandr )"
hdmic="$( echo "$xr" | grep -o "HDMI-0 connected" )"
dvic="$( echo "$xr" | grep -o "DVI-I-2-1 connected" )"

mode="2560x1080"
rot="normal"

for i in "$@"
do
    if [ "$i" = "-g" ] || [ "$i" = "--geforce-now" ]
    then
        mode="1920x1080"
    elif [ "$i" = "-p" ] || [ "$i" = "--portrait" ]
    then
        rot="left"
    fi
done


if ! [ "$hdmic" = "" ]
then
    if ! [ "$dvic" = "" ]
    then
        if [ "$rot" = "normal" ]
        then
            xrandr --output HDMI-0 --mode "$mode" --primary --rotate "$rot" --pos 1920x0 --output eDP-1-1 --mode 1920x1080 --pos 1920x1080 --output DVI-I-2-1 --mode 1920x1080 --pos 0x1080
        else
            xrandr --output HDMI-0 --mode "$mode" --primary --rotate "$rot" --pos 1920x0 --output eDP-1-1 --mode 1920x1080 --pos 0x1080 --output DVI-I-2-1 --mode 1920x1080 --pos 0x0
        fi
    else
        if [ "$rot" = "normal" ]
        then
            xrandr --output HDMI-0 --mode "$mode" --primary --rotate "$rot" --pos 1920x0 --output eDP-1-1 --mode 1920x1080 --pos 1920x1080
        else
            xrandr --output HDMI-0 --mode "$mode" --primary --rotate "$rot" --pos 1920x0 --output eDP-1-1 --mode 1920x1080 --pos 0x0
        fi
    fi
else
    if ! [ "$dvic" = "" ]
    then
        xrandr --output eDP-1-1 --mode 1920x1080 --primary --pos 1920x0 --output DVI-I-2-1 --mode 1920x1080 --pos 0x0
    else
        xrandr --output eDP-1-1 --mode 1920x1080 --primary --pos 0x0
    fi
fi
