#!/usr/bin/env sh

. std.sh

if [ ! -t 0 ]; then
    stdinfl="$(mktemp)"
    cp -f -- /dev/stdin "$stdinfl"
fi

[ -s "$stdinfl" ] || {
    exec >&-
    exit 1
}

cat -- "$stdinfl"
rm -f -- "$stdinfl"
exit 0
