#!/usr/bin/env sh

. io.sh
. std.sh
. util.sh

tmp="$(mktemp)" || exit 1
stack="$(mktemp)" || {
    rm -f -- "$tmp"
    exit 1
}
trap 'rm -f -- "$tmp" "$stack"' EXIT

for base_dir; do
    (
        std_cd "$base_dir"

        printf '%s\0' '.' > "$stack"
        while [ -s "$stack" ]; do
            dir="$(std_fpop_headz 1 "$stack")"
            real_dir="$(realpath -s -- "$dir")"
            find "$real_dir" -mindepth 1 -maxdepth 1 -print0 | tee -- "$tmp"
            stest -dx0 < "$tmp" >> "$stack"
        done
    )
done
