#!/usr/bin/env sh

. io.sh
. std.sh

tmp="$(mktemp)" || exit 1
stack="$(mktemp)" || {
    rm -f -- "$tmp"
    exit 1
}
trap 'rm -f -- "$tmp" "$stack"' EXIT

printf '%s\0' '.' > "$stack"
while [ -s "$stack" ]; do
    dir="$(std_fpop_headz 1 "$stack")"
    find "$dir" -mindepth 1 -maxdepth 1 "$@" -print0 | tee -- "$tmp"
    stest -dx0 < "$tmp" >> "$stack"
done
