#!/usr/bin/env sh

if [ -t 0 ]; then
    printf "%s\0" "$@" 
else
    cat
fi | sed -z 's/[x+]/ /g' | awk '
    BEGIN {
        RS = "\0";
        max_x = 0;
        max_y = 0;
    } {
        x = $1 + $3;
        y = $2 + $4;
        if (x > max_x)
            max_x = x;
        if (y > max_y)
            max_y = y;
    } END {
        printf("%dx%d\n", max_x, max_y);
    }
'
