#!/usr/bin/env sh
# Pipe stdin to stdout if present and non-empty, else
# evaluate the given arguments and output its stdout.

. shellverbose.sh

if [ ! -t 0 ]; then
    stdinfl="$(mktemp)"
    cp -f -- /dev/stdin "$stdinfl"
fi

[ -s "$stdinfl" ] && {
    cat -- "$stdinfl"
    rm -f -- "$stdinfl"
    exit 0
}

rm -f -- "$stdinfl"
exec "$@"
