#!/usr/bin/env sh
# Adapted from https://stackoverflow.com/a/30022297/8403070.

. std.sh

stty -icanon -echo < /dev/tty > /dev/tty
char="$(dd bs=1 count=1 < /dev/tty 2> /dev/null)" || exit 1
stty icanon echo < /dev/tty > /dev/tty
printf "%s" "$char"
