#!/usr/bin/env sh

. std.sh

output_path="$1"
shift 1
# rest of the arguments are (input_path, geometry)...

total_size="$(printf "%s\0" "$@" | xargs -r0 argn 1 -1 2 | get-max-geometry)"

# I'm sorry for what I have done...
{
    printf "%s\0" "$@" | xargs -r0 -n 2 sh -c '
        tmp="$(mktemp)"
        convert "$1" -resize "${2%%+*}^" -gravity center -crop "${2%%+*}+0+0" +repage "$tmp" >&2
        printf "%s\0" "$tmp" "$2"
    ' --
} | total_size="$total_size" output_path="$output_path" xargs -r0 sh -c '
    {
        printf "%s\0" -size "$total_size" xc:black
        printf "%s\0" "$@" | xargs -r0 -n 2 sh -c "
            printf \"%s\0\" \"\$1\" -geometry \"+\${2#*+}\" -composite
        " --
        printf "%s\0" "$output_path"
    } | xargs -r0 convert
    printf "%s\0" "$@" | xargs -r0 argn 0 -1 2 | xargs -r0 rm -f --
' --
