#!/usr/bin/env sh

. shellverbose.sh

if [ "$1" -ne 0 ]; then
    tostate=enable
else
    tostate=disable
fi

xinput --list \
    | grep -o "$2\s\+.*id=[0-9]\+" \
    | sort \
    | grep -o '[0-9]\+$' \
    | xargs -d '\n' -n 1 xinput --"$tostate"
