#!/usr/bin/env sh
# Redraw status bar every minute.

. std.sh

statbarset
statbaravlsyutick &

prevDate="$(date +"%R")"

while [ "$prevDate" = "$(date +"%R")" ]; do
    sleep 1s
done

sleep 1s

while :; do
    dwmbar-set &
    sleep 1m
done
