#!/usr/bin/env sh

until [ -f "ProjectSettings/ProjectVersion.txt" ]; do
    [ "$PWD" = "/" ] && exit 1
    cd ..
done

cmd="$1"
shift
case "$cmd" in
    astyle)
        astyle --mode=cs --project=.astylerc "$@"
        ;;
    dotnet)
        project="${PWD##*/}"
        dotnet format "$project.csproj" "$@"
        ;;
esac
