#!/usr/bin/env sh

. std.sh

players="$(playerctl -l -i "$PLAYERCTLSELIGNORE")"

case "$(printf "%s\n" "$players" | wc -l)" in
    0) [ -n "$PLAYERCTLSELFALLBACK" ] && [ "$PLAYERCTLSELFALLBACK" -ne 0 ] && playerctl -p "$PLAYERCTLSELIGNORE" "$@";;
    1) playerctl "$@";;
    *) printf "%s\n" "$players" | execmenu | xargs -d '\n' -rI PLAYER playerctl -p PLAYER "$@";;
esac
