#!/usr/bin/env sh
# Set the brightness of the screen(s?). This only affects the laptop screen on my system.

. std.sh

lck -rq xbacklight

execmenu -p "Enter brightness %:" < /dev/null \
    | sed -e 's/\..*//g' -e 's/[^[:digit:]].*//g' \
    | xargs -d '\n' -rI '{}' sudo xbacklight $XBACKLIGHT_ARGS -set '{}'

lck -uq xbacklight
