#!/usr/bin/env sh

. evalverbose.sh

make() {
    [ -f Makefile ] && exec execaux "$0" "$@"
}

make "$@"
while [ "$PWD" != "/" ]; do
    cd ..
    make "$@"
done

printf "%s\n" "No Makefile found in tree." >&2
exit 1
