#!/usr/bin/env sh

eval "$(evalverbose)"

preargs="${NSXIV_ARGS_PRE:-"-a0"}"
postargs="$NSXIV_ARGS_POST"

{   printf "%s\0" $preargs
    for i; do
        if [ "$i" != "--" ]; then
            printf "%s\0" "$i"
        else
            printf "%s\0" $postargs --
        fi
    done
} | exec xargs -0 execaux "$0"
