#!/usr/bin/env sh

unset XDG_CURRENT_DESKTOP

[ "$#" -eq 1 ] && {
    case "$1" in
        --help|--manual|--version) :;;
        *)
            if [ -e "$1" ]; then
                arg="$(realpath -P -- "$1")"
                [ ! -s "$1" ] || {
                    ft="$(file --mime-type --brief "$arg")" \
                    && [ "$ft" != "text/html" ] \
                    && [ "${ft%%/*}" = "text" ]
                } && exec "$EDITOR" -- "$1"
            else
                arg="$1"
            fi
            ulckget xdgopenlog || printf "%s; %s\n" "$(date +"%s")" "$arg" >> "$(getpath -f -- xdgopenlog)"
            ;;
    esac
}

exec execaux "$0" "$@"
