#!/usr/bin/env sh

. shellverbose.sh

conf_dir="${XDG_CACHE_HOME:-"$HOME/.cache"}/scripts/logboot"
mkdir -p -- "$conf_dir"
pfx="$conf_dir/$(date --iso-8601=seconds)"
systemd-analyze blame > "$pfx.log"
systemd-analyze plot > "$pfx.svg"
