#!/usr/bin/env python3


from sys import argv
import json
import requests


for arg in argv[1:]:
    print(f"{arg}: ", end="")

    try:
        print(
            requests.get(f"https://api.dictionaryapi.dev/api/v2/entries/en/{arg}")
            .json()[0]["meanings"][0]["definitions"][0]["definition"]
            .strip()
        )
    except Exception:
        print("Not found")
