#!/usr/bin/env python3


import sys

import requests


def main() -> int:
    for phrase in sys.argv[1:]:
        definition = (
            requests.get(
                f"https://api.dictionaryapi.dev/api/v2/entries/en/{phrase}",
                timeout=10,
            )
            .json()[0]["meanings"][0]["definitions"][0]["definition"]
            .strip()
        )

        print(f"{phrase}: {definition}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
