[package]
name = "sandwichline"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
clap = { version = "4.0", features = ["derive"] }
termion = "2.0.1"
isatty = "0.1"
rand = "0.8"
