#!/usr/bin/env sh

eval "$(evalverbose)"

md() {
    printf "%s\0" "$@" \
        | IFS= xargs -0r -I {} sh -c 'pandoc -- {} | minify --mime=text/html' \
        | xins -R -- lynx -dump -stdin \
        | less
}

if [ "$#" -ne 0 ]; then
    md "$@"
else
    md ./*.md
fi
