#!/usr/bin/env sh
# Overwrite a file.

eval "$(evalverbose)"

cp "$@" || {
    printf "%s\n" "Could not overwrite:" "$@"
    exit 1
}

paths="$(printf "%s" "$@" | sed 's/\s.*$//')"

rm "$paths" || {
    printf "%s\n" "Could not remove:" "$paths"
    exit 1
}
