#!/usr/bin/env sh
# Swap two files.

. evalverbose.sh

fl="$(printf "%s\n" "$1" | sed 's,/*$,,')"
other="$(printf "%s\n" "$2" | sed 's,/*$,,')"
tmp="$(getnewpath "$fl")"
mv -n -- "$fl" "$tmp"
mv -n -- "$other" "$fl"
mv -n -- "$tmp" "$other"
