#!/usr/bin/env sh

. evalverbose.sh

unset optremovetmp
while getopts "hr" OPT; do
    case "$OPT" in
        h)
            printf "%s" \
"$0 [OPTION]...
   -h   display this help and exit
   -r   remove temporary files before exiting
"
            exit 0
            ;;
        r) optremovetmp=1;;
        *) printf "Invalid option given: %s\n" "$OPT"; exit 1;;
    esac
done
shift "$((OPTIND - 1))"

if [ "$#" -eq 0 ]; then
    if [ -t 0 ]; then
        yesno "No file given, trim all PDFs in the current directory? [y/N]\n" || exit 0
        find '.' -mindepth 1 -maxdepth 1 -iname "*.pdf" -print0 | xargs -0r trimpdf
    else
        xargs -0r trimpdf
    fi
else
    for i; do
        [ "$(file --mime-type -b -- "$i")" != "application/pdf" ] && continue

        tmp="$(mktemp -p /tmp "trimpdf-${i##*"/"}-XXXXXX.pdf")" || continue

        cp -f -- "$i" "$tmp" || continue

        rm -f -- "$i"

        pdf-crop-margins -o "$i" -- "$tmp" || continue
        # pdf-crop-margins cannot cut perfectly on the first try
        tmp1="$(mktemp --suffix .pdf)" || continue
        tmp2="$(mktemp --suffix .pdf)" || continue
        cp -f -- "$i" "$tmp1" || continue
        j=-1
        while [ $((j += 1)) -lt 2 ]; do
            pdf-crop-margins -o "$tmp2" -- "$tmp1"
            pdf-crop-margins -o "$tmp1" -- "$tmp2"
        done

        cp -f -- "$tmp1" "$i"

        [ "$optremovetmp" = 1 ] && rm -f -- "$tmp" "$tmp1" "$tmp2"
    done
fi
