#!/usr/bin/env sh

eval "$(evalverbose)"

[ ! -e "$1" ] && {
    format="$1"
    shift
}

name="${1%.*}"
case "$format" in
    zip ) zip -r  "$name.zip"    "$@";;
    7z  ) 7z a    "$name.7z"     "$@";;
    *   ) tar czf "$name.tar.gz" "$@";;
esac
