#!/usr/bin/env sh

. evalverbose.sh

[ ! -e "$1" ] && {
    format="$1"
    shift
}

name="$(printf "%s\0" "$1" | sed -z 's|/*$||;s|^.*/||')"
case "$format" in
    zip ) zip -r  "$name.zip"    "$@";;
    7z  ) 7z a    "$name.7z"     "$@";;
    *   ) tar czf "$name.tar.gz" "$@";;
esac
