#!/usr/bin/env sh

if [ -n "$KITTY_PID" ]; then
    kitty +kitten icat --stdin no clear < /dev/null > /dev/tty
elif [ -n "$UEBERZUG_FIFO" ]; then
    jq -cn \
        --arg action remove \
        --arg identifier PREVIEW \
        '{
            action: $action,
            identifier: $identifier,
        }' > "$UEBERZUG_FIFO"
fi
