#!/usr/bin/env sh

. shellverbose.sh

set -e

[ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ] \
    || [ -n "$LF_NO_IMAGE_PREVIEW" ] \
    && exec lf "$@"

if command -v -- ueberzugpp > /dev/null 2>&1; then
    cleanup() {
        exec 3>&-
        ueberzugpp cmd -s "$UEBERZUGPP_SOCKET" -a exit
    }

    cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}/lf"
    mkdir -p -- "$cachedir" 2> /dev/null || [ -d "$cachedir" ]

    UEBERZUGPP_PID_FILE="$UEBERZUG_TMP_DIR/.$(uuidgen)"
    ueberzugpp layer --silent --no-stdin --use-escape-codes --pid-file "$UEBERZUGPP_PID_FILE"

    UEBERZUGPP_PID=$(cat "$UEBERZUGPP_PID_FILE")
    rm -- "$UEBERZUGPP_PID_FILE"

    UEBERZUGPP_SOCKET="$UEBERZUG_TMP_DIR/ueberzugpp-${UEBERZUGPP_PID}.socket"

    export UEBERZUGPP_PID
    export UEBERZUGPP_SOCKET

    trap cleanup HUP INT QUIT TERM EXIT

    lf "$@" 3>&-
elif command -v -- ueberzug > /dev/null 2>&1; then
    cleanup() {
        exec 3>&-
        rm -- "$UEBERZUG_FIFO"
    }

    fifodir="${XDG_CACHE_HOME:-"$HOME/.cache"}/lf/fifos"
    mkdir -p -- "$fifodir" 2> /dev/null || [ -d "$fifodir" ]
    UEBERZUG_FIFO="$fifodir/ueberzug-$$"

    mkfifo -- "$UEBERZUG_FIFO"
    trap 'cleanup' EXIT INT TERM HUP QUIT

    ueberzug -s layer < "$UEBERZUG_FIFO" &
    exec 3> "$UEBERZUG_FIFO"

    export UEBERZUG_FIFO

    lf "$@" 3>&-
else
    lf "$@"
fi
