#!/usr/bin/env sh

. shellverbose.sh

"$PAD" -- sh -c '
    if yay -Syu; then
        [ -n "$YAY_ALWAYS_CLEAN_CACHE" ] \
            && [ "$YAY_ALWAYS_CLEAN_CACHE" -ne 0 ] \
            && yay -Scc --noconfirm > /dev/null 2>&1
        color green "All done."
    else
        color red "ERROR(s) encountered."
    fi
    flushterm
    readstr
'
