#!/usr/bin/env sh

eval "$(evalverbose)"

"$PAD" -- sh -c '
    if yay -Syu; then
        color green "All done."
    else
        color red "ERROR(s) encountered."
    fi
    flushterm
    readstr
'
