#!/usr/bin/env sh

eval "$(evalverbose)"

"$PAD" -- '
    update > /dev/null 2>&1 &
    time yay -Syu || color red "ERROR(s) encountered."
    jobs %% && printf "Waiting for [update].\n"
    wait
    color green "All done. Check for errors."
    flushterm
    readstr
'
