#!/usr/bin/env sh

. shellverbose.sh

assertroot || exit 1

devs="$(lsblk -nrpo "name,label,mountpoint")"

while IFS='' read -r label mp _; do
    printf "%s\n" "$devs" | while read -r devname devlabel devmp _; do
        [ "$(env printf "$devlabel")" = "$label" ] \
            && [ -z "$devmp" ] \
            && mkdir -p -- "$mp" \
            && mount "$devname" "$mp" \
            && {
                chown :wheel -- "$mp"
                chmod 770 -- "$mp"
            }
    done
done < "$(getpath -f -- mounts)"

exit 0
