#!/usr/bin/env sh
# Adjust displays with xrandr.

. evalverbose.sh

xr="$(xrandr)"
hdmic="$(printf "%s" "$xr" | grep -o "$XRH_HDMI connected")"
dvic="$(printf "%s" "$xr" | grep -o "$XRH_DVI connected")"

mode="2560x1080"
rot="normal"

for i; do
    if [ "$i" = "-g" ] || [ "$i" = "--geforce-now" ]; then
        mode="1920x1080"
    elif [ "$i" = "-p" ] || [ "$i" = "--portrait" ]; then
        rot="left"
    elif [ "$i" = "hdmi" ]; then
        hdmic=""
    elif [ "$i" = "dvi" ]; then
        dvic=""
    fi
done


if ! [ "$hdmic" = "" ]; then
    if ! [ "$dvic" = "" ]; then
        if [ "$rot" = "normal" ]; then
            xrandr --output "$XRH_HDMI" --mode "$mode"   --primary --rotate "$rot" --pos 1920x0 \
                   --output "$XRH_EDP"  --mode 1920x1080                           --pos 1920x1080 \
                   --output "$XRH_DVI"  --mode 1920x1080                           --pos 0x1080
        else
            xrandr --output "$XRH_HDMI" --mode "$mode"   --primary --rotate "$rot" --pos 1920x0 \
                   --output "$XRH_EDP"  --mode 1920x1080                           --pos 0x1080 \
                   --output "$XRH_DVI"  --mode 1920x1080                           --pos 0x0
        fi
    else
        if [ "$rot" = "normal" ]; then
            xrandr --output "$XRH_HDMI" --mode "$mode"   --primary --rotate "$rot" --pos 0x0 \
                   --output "$XRH_EDP"  --mode 1920x1080                           --pos 2560x0
        else
            xrandr --output "$XRH_HDMI" --mode "$mode"   --primary --rotate "$rot" --pos 1920x0 \
                   --output "$XRH_EDP"  --mode 1920x1080                           --pos 0x0
        fi
    fi
else
    if ! [ "$dvic" = "" ]; then
        xrandr --output "$XRH_EDP"      --mode 1920x1080 --primary                 --pos 1920x0 \
               --output "$XRH_DVI"      --mode 1920x1080                           --pos 0x0
    else
        xrandr --output "$XRH_EDP"      --mode 1920x1080 --primary                 --pos 0x0
    fi
fi
