#!/usr/bin/env sh
# Mount a remote drive with rclone based on the given drive code.
# TODO: Add support for non-cached mounting via argument parsing.

. evalverbose.sh

case "$1" in
    one) name="onedrive";;
    open) name="opendrive";;
    *) printf "%s\n" "No drive code given, exiting."; exit 0;;
esac

[ -d /mnt/"$name" ] || sudo mkdir -- /mnt/"$name"
sudo rclone mount --daemon --allow-other \
                  --vfs-cache-mode full --cache-dir ~/data/rclone \
                  --vfs-cache-max-age 0h5m0s "$1": /mnt/"$name"
