#!/usr/bin/env sh

apps="$(ps -eocommand)"

if printf "%s" "$apps" | grep -q "^/opt/spotify/spotify$"
then
    app="spotify"
elif printf "%s" "$apps" | grep -q "^vlc"
then
    app="vlc"
fi

printf "%s\n" "$app"
