#!/usr/bin/env sh
# Execute a file every time it is modified.

eval "$(evalverbose)"

execname="${0##*/}"

printhelp() {
    printf "%s\n" \
"$execname [OPTION...] [FILES...] -- [FILES...]
   -o, --once
       Exit after the first execution.
   --no-once
       Revert -o.
   -h, --help
       Print help message."
}

printusage() {
    printf "Option [%s] is not valid.\n\n" "$1" >&2
    printhelp
}

logerrq() {
    printf "[ERROR]: %s\n" "$1" >&2
    exit 1
}

assertarg() {
    [ -z "$3" ] && logerrq "Expected $2 argument to $1, exiting."
}

assertfl() {
    [ -f "$1" ] || logerrq "No such file as $1, exiting."
}

parseargs() {
    while [ -n "$1" ]; do
        if [ "${1%"${1#?}"}" = "-" ]; then
            if [ "${1%"${1#??}"}" != "--" ]; then
                sopt="${1#?}"

                while [ -n "$sopt" ]; do
                    opt="${sopt%"${sopt#?}"}"

                    case "$opt" in
                        o) parseargs --once;;
                        h) parseargs --help;;
                        *) printusage "-$opt"; exit 0;;
                    esac

                    sopt="${sopt#?}"
                done
            else
                opt="${1#??}"

                case "$opt" in
                    once     ) optonce="1";;
                    no-once  ) optonce="0";;
                    help     ) printhelp; exit 0;;
                    ""       ) shift; break;;
                    *        ) printusage "--$opt"; exit 0;;
                esac
            fi
        else
            argv="$argv $1"
        fi

        shift
    done

    for i; do
        argv="$argv $i"
    done
}

processargs() {
    [ -z "$argv" ] && logerrq "No arguments to execute given."
    execpath="$(printf "%s\n" "$argv" | headw 1)"
}

execute() {
    inotifywait -e move_self -- "$execpath" > /dev/null 2>&1
    pid="$(cat -- "$pidfl")"
    kill -s 0 "$pid" 2> /dev/null && {
        env kill -s INT --timeout 1000 TERM --timeout 1000 KILL "$pid" 2> /dev/null \
            || logerrq "Could not kill PID $pid, exiting."
    }
    waitfl "$execpath" && sleep 0.5
    while kill -s 0 "$pid" 2> /dev/null; do
        sleep 0.1
    done
    kill %% 2> /dev/null
    $argv &
    printf "%s" "$!" > "$pidfl"
}

main() {
    [ "$optonce" = "1" ] && {
        inotifywait -e move_self -- "$execpath" > /dev/null 2>&1
        eval "$execpath"
        exit 0
    }

    pidfl="$(mktemp)"
    while true; do
        execute
    done
}

parseargs "$@"
processargs
trap 'kill 0 2>&1' INT TERM EXIT
main
