#!/usr/bin/env sh

. shellverbose.sh

. utility.sh # unused, included for external configs

get_headsetcontrol_eval() {
    { headsetcontrol -b -m || sudo headsetcontrol -b -m; } 2> /dev/null \
        | grep -E '(Battery|Chat-Mix):\s+([0-9]+|Charging)' \
        | tr -d ' -' \
        | tr ':' '=' \
        | tr -d '%' \
        | sed 's/^ChatMix/mix/;s/^Battery/battery/'
}

configfl="${XDG_CONFIG_HOME:-"$HOME/.config"}/scripts/headsetcontrol2mpris/config.sh"
if [ -f "$configfl" ]; then
    . "$configfl"
    hasconfig() {
        true
    }
else
    hasconfig() {
        false
    }
fi

hasconfig || update() {
    # shellcheck disable=SC2154
    [ "$last_mix" != "$mix" ] && {
        if [ "$mix" = 128 ]; then
            playerctl -a pause
        elif [ "$last_mix" = 128 ]; then
            playerctl -a play
        fi
    }
}

while :; do
    (
        set -e

        eval "$(get_headsetcontrol_eval | sed 's/^/last_/')"

        while :; do
            sleep 2

            eval "$(get_headsetcontrol_eval)"

            (update) || :

            last_mix="$mix"
            # shellcheck disable=SC2034,SC2154
            last_battery="$battery"
        done
    )
    sleep 5
done
