#!/usr/bin/env sh
# Sync mails as a daemon (though it does not fork out).

. evalverbose.sh

interval="${*:-"180s"}"

sleep 15s

while true; do
    syncmail
    polybar-msg action '#mail.hook.0'
    sleep "$interval"
done
