#!/usr/bin/env sh
# Get directories or the directories of files with given codes.

for i
do
    loc="$(getloc "$i")" || {
        loc="$(getfl "$i")" || continue
        loc="$(dirname "$loc")"
    }
    expandpath "$loc"
done
