#!/usr/bin/env sh

eval "$(evalverbose)"

[ "$#" -lt 1 ] && exit 1
message="$1"
shift

toplevel="$(git rev-parse --show-toplevel)"

if [ "$#" -ne 0 ] && [ -n "$*" ]; then
    fls="$(
        printf "%s\n" "$@" \
            | xargs -d '\n' -rn 1 realpath "--relative-to=$toplevel" -- \
            | sed 's|^src/||'
    )"
else
    fls="$(
        {
            {   git diff --name-status
                git diff --cached --name-status
            } | cut -d'	' -f2-
            git ls-files -o --exclude-standard --directory | stest -d | sed 's|$|/*|'
            git ls-files -o --exclude-standard | stest -dd
        } | uniqs \
          | xargs -d '\n' -rn 1 realpath "--relative-to=$toplevel" --
    )"
    IFS='
'
    set -o noglob
    set -- $fls
    fls="$(printf "%s\n" "$fls" | sed 's|^src/||')"
fi

if [ "$#" -eq 1 ]; then
    git add -- "$1" && git commit -m "$message $fls"
else
    git add -- "$@" && git commit -m "$message $(
        printf "%s\n" "$fls" | sed 's/$/, /' | sort | tr -d '\n' | sed 's/, \([^ ]*\), $/ and \1/'
    )"
fi
