[package]
name = "pathfinder"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
clap = { version = "4.0", features = ["derive"] }
isatty = "0.1"
etcetera = "0.8"
once_cell = "1.14.0"
