#!/usr/bin/env sh
# Adapted from https://github.com/Chrysostomus/bspwm-scripts

direction="$1"
size="${2:-30}"

case "$direction" in
    west ) bspc node @west -r -"$size"  || bspc node @east -r -"$size" ;;
    east ) bspc node @west -r +"$size"  || bspc node @east -r +"$size" ;;
    north) bspc node @south -r -"$size" || bspc node @north -r -"$size";;
    south) bspc node @south -r +"$size" || bspc node @north -r +"$size";;
esac
