#!/usr/bin/env sh

. std.sh

begin_date="$(date -d "$1" +%s)"
end_date="$(date -d "$2" +%s)"
diff="$((end_date - begin_date))"

printf "%s days, %s hours, %s minutes, %s seconds\n" \
    "$((diff / 86400))" \
    "$((diff % 86400 / 3600))" \
    "$((diff % 3600 / 60))" \
    "$((diff % 60))"
