#!/usr/bin/env sh
# Duplicate given files and print the duplicate's paths in the format the originals were input.

. std.sh

for i; do
    newpath="$(backuppath "$i")"
    cp -r -- "$i" "$newpath"
    printf "%s\n" "$newpath"
done
