#!/usr/bin/env sh

. shellverbose.sh

[ "$#" -eq 0 ] && exec locate -- ""
[ "$#" -eq 1 ] && exec locate -- "$1"

prog="${0##*/}"
vec="argv"

std::vector -- "$prog" "$vec" new
std::vector -- "$prog" "$vec" push_back "$@"
query="$(std::vector -- "$prog" "$vec" pop_back)"
db="$(std::vector -- "$prog" "$vec" pop_back)"
eval "$(std::vector -- "$prog" "$vec" eval)"

locate -d "/var/lib/mlocate/$(printf "%s" "/mnt/$db" | sha512sum | cut -d' ' -f1).db" "$@" -- "$query"
