#!/usr/bin/env sh
# Pings specified addresses and notifies the user when all succeeded once.

. std.sh

t="5s"

for i; do
    sleep "$t"
    until ping -c 1 "$i"; do
        sleep "$t"
    done
done

notify-send -u critical -t 0 "🌐 pingnotif" "Connected to the specified addresses on $(date)."
