#!/usr/bin/env sh

. std.sh

kitty_add() {
    _pid="$1"
    file="$2"
    pane_width="$3"
    pane_height="$4"
    pane_x="$5"
    pane_y="$6"
    shift 6

    kitty +kitten icat \
        --transfer-mode file \
        --stdin no \
        --scale-up \
        --place "${pane_width}x${pane_height}@${pane_x}x${pane_y}" \
        -- "$file" < /dev/null > /dev/tty

    [ "$#" -ne 0 ] && kitty_add "$@"
}

kitty_remove() {
    kitty +kitten icat \
        --transfer-mode file \
        --stdin no \
        --clear < /dev/null > /dev/tty
}

generic_add() {
    pid="$1"
    file="$2"
    pane_width="$3"
    pane_height="$4"
    pane_x="$5"
    pane_y="$6"
    shift 6

    [ -e "$tmpdir/$pid" ] && remove "$pid"

    tmpfl="$(mktemp)"
    termsize "$tmpfl" < /dev/tty > /dev/tty
    term_size_pixels="$(cat -- "$tmpfl")"
    rm -f -- "$tmpfl"
    term_width="${term_size_pixels%" "*}"
    term_height="${term_size_pixels#*" "}"
    if [ -n "$LF_LEVEL" ] && [ "$LF_LEVEL" -gt 0 ]; then
        term_cols="$(($(tput cols) + pane_x))"
        term_lines="$((pane_height))"
    else
        term_cols="$(tput cols)"
        term_lines="$(tput lines)"
    fi

    image_width="$(printf "%d\n" "$(printf "scale = 0; %d.0 / %d.0 * %d.0\n" "$term_width" "$term_cols" "$pane_width" | bc)")"
    image_height="$(printf "%d\n" "$(printf "scale = 0; %d.0 / %d.0 * %d.0\n" "$term_height" "$term_lines" "$pane_height" | bc)")"
    image_path="$tmpdir/$pid-img-$(basename -- "$file")"

    ueberzugpp layer --no-stdin --silent --use-escape-codes --pid-file "$tmpdir/$pid" < /dev/null > /dev/null
    convert "$file" \
        -resize "${image_width}x${image_height}" \
        -gravity center \
        "$image_path"
    ueberzugpp cmd \
        -s "$ueberzugpp_tmpdir/ueberzugpp-$(cat -- "$tmpdir/$pid").socket" \
        -a add \
        -i PREVIEW \
        -x "$pane_x" \
        -y "$pane_y" \
        --max-width "100000" \
        --max-height "100000" \
        -f "$image_path" < /dev/null > /dev/null

    [ "$#" -ne 0 ] && generic_add "$@"
}

generic_remove() {
    pid="$1"
    shift 1

    [ -e "$tmpdir/$pid" ] && {
        ueberzugpp_pid="$(cat -- "$tmpdir/$pid")"
        kill -s KILL -- "$ueberzugpp_pid"
        rm -f -- \
            "$ueberzugpp_tmpdir/ueberzugpp-$ueberzugpp_pid.socket" \
            "$tmpdir/$pid" \
            "$tmpdir/$pid"-img-*
    }

    [ "$#" -ne 0 ] && generic_remove "$@"
}

choose_method() {
    if [ -n "$KITTY_PID" ]; then
        add() kitty_add "$@"
        remove() kitty_remove "$@"
    else
        add() generic_add "$@"
        remove() generic_remove "$@"
    fi
}

tmpdir="${TMPDIR:-/tmp}/previewimage"
mkdir -p -- "$tmpdir" || [ -d "$tmpdir" ] || exit 1

ueberzugpp_tmpdir="${TMPDIR:-/tmp}"

choose_method

case "$1" in
    add) shift 1; add "$@";;
    remove) shift 1; remove "$@";;
    *) exit 1;;
esac
