#!/usr/bin/env sh

. std.sh

ytdl() {
    url="$1"
    shift
    command ytdl "$@" -- "$url"
}

gldl() {
    url="$1"
    shift
    command gldl "$@" -- "$url"
}

if [ -n "$YTDL_OR_GLDL_REVERSE" ] && [ "$YTDL_OR_GLDL_REVERSE" -ne 0 ]; then
    auto() {
        ytdl "$url" "$@" || gldl "$url" "$@"
    }
else
    auto() {
        gldl "$url" "$@" || ytdl "$url" "$@"
    }
fi

while IFS= read -r url; do
    case "$url" in
        ""|"#"*) continue;;
        "@ytdl"*) ytdl "${url#"@ytdl"}" "$@";;
        "@gldl"*) gldl "${url#"@gldl"}" "$@";;
        *) auto "$@";;
    esac
done
