#!/usr/bin/env sh

. std.sh

vector() {
    std::vector -c t -n bspwm-stalker stalkees "$@"
}

toggle_node() {
    node="$1"

    vector ensure
    if vector find "$node"; then
        vector erase "$(vector find "$node")"
    else
        vector push_back "$node"
    fi
}

if [ "$#" -eq 0 ]; then
    toggle_node "$(bspc query -N -n .focused)"
else
    for node; do
        toggle_node "$node"
    done
fi
