#!/usr/bin/env sh

. std.sh

[ $# -ne 2 ] && exit 1

action="$1"
[ "$action" != "f" ] && [ "$action" != "s" ] && exit 1
direction="$2"

m="$(bspc query -m focused -M)"

setn() {
    n="$(bspc query -n "$direction" -N)" && [ "$(bspc query -n "$n" -M)" = "$m" ]
}

setn || {
    direction="$(printf "%s\n" "$direction" | END= fmaps west=east east=west south=north north=south)"
    setn || exit 1
}

bspc node "-$action" "$direction"
