#!/usr/bin/env sh

eval "$(evalverbose)"

xinput --list \
    | grep -o "$MAPTOUCH_ROOT_DEVNAME\s\+.*id=[0-9]\+" \
    | sed "s/\s\+id=[0-9]\+//" \
    | sort \
    | xargs -r -d '\n' -I DEV xinput map-to-output DEV "$XRH_EDP"
