#!/usr/bin/env sh

eval "$(evalverbose)"

assertroot || exit 1

devs="$(lsblk -nrpo "name,label,mountpoint")"

while IFS='' read -r label mp _; do
    printf "%s\n" "$devs" | while read -r devname devlabel devmp _; do
        [ "$(env printf "$devlabel")" = "$label" ] && [ -z "$devmp" ] && mount "$devname" "$mp"
    done
done < "$(getpath -f -- mounts)"

exit 0
