#!/usr/bin/env sh
# Set X keyboard properties.

# shellcheck disable=SC2154

. execinfo.sh
. io.sh
. prefix.sh
. shellverbose.sh

modmap_dir="${XDG_CONFIG_HOME:-$HOME/.config}/scripts/setxkb/xmodmap"
xset_dir="${XDG_CONFIG_HOME:-$HOME/.config}/scripts/setxkb/xset"
def_exprs_dir="$std_dataprefix/setxkb/default"

optdefault=0
while getopts "dh" OPT; do
    case "$OPT" in
        d) optdefault=1;;
        h)
            printf "%s" \
"$execname [OPTION...] [keymap]?
   -d      load default mappings and exit
   -h      display this help and exit
" >&2
            exit 0
            ;;
        *)
            printf "Invalid option given: %s\n" "$OPT" >&2
            exit 1
            ;;
    esac
done
shift "$((OPTIND - 1))"

km="${1:-"$(xkb-switch)"}"
[ "$#" -gt 0 ] && {
    shift
    std_logerr "extra operands given, ignoring: $*"
}

def_exprs="$def_exprs_dir/$km"

[ "$optdefault" -ne 0 ] && {
    std_assert_can_query_prefix
    [ -e "$def_exprs" ] || std_logerrq "no default configuration exists for keymap $km"
    exec xmodmap - < "$def_exprs"
}

cat -- \
    "$def_exprs" \
    "$modmap_dir/*" \
    "$modmap_dir/$km" \
    2> /dev/null \
    | xmodmap -

cat -- \
    "$xset_dir/*" \
    "$xset_dir/$km" \
    2> /dev/null \
    | tr '[:space:]' '\0' \
    | xargs -r0 xset
