#!/usr/bin/env sh
# Set X keyboard properties.

# shellcheck disable=SC2154

. execinfo.sh
. io.sh
. prefix.sh
. shellverbose.sh

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/scripts/setxkb"
modmap_dir="$config_dir/xmodmap"
xset_dir="$config_dir/xset"
pre_exec_dir="$config_dir/pre_exec"
post_exec_dir="$config_dir/post_exec"
def_exprs_dir="$std_dataprefix/setxkb/default"

optdefault=0
while getopts "dh" OPT; do
    case "$OPT" in
        d) optdefault=1;;
        h)
            printf "%s" \
"$execname [OPTION...] [keymap]?
   -d      load default mappings and exit
   -h      display this help and exit
" >&2
            exit 0
            ;;
        *)
            printf "Invalid option given: %s\n" "$OPT" >&2
            exit 1
            ;;
    esac
done
shift "$((OPTIND - 1))"

if [ "$#" -eq 0 ]; then
    km="$(xkb-switch)"
elif [ "$#" -eq 1 ]; then
    km="$1"
    shift
fi

[ "$#" -ne 0 ] && {
    std_logerr "extra operands given, ignoring: $*"
    set --
}

def_exprs="$def_exprs_dir/$km"

[ "$optdefault" -ne 0 ] && {
    std_assert_can_query_prefix
    [ -e "$def_exprs" ] || std_logerrq "no default configuration exists for keymap $km"
    exec xmodmap - < "$def_exprs"
}

[ -x "$pre_exec_dir/*" ] && "$pre_exec_dir/*"
[ -x "$pre_exec_dir/$km" ] && "$pre_exec_dir/$km"

cat -- \
    "$def_exprs" \
    "$modmap_dir/*" \
    "$modmap_dir/$km" \
    2> /dev/null \
    | xmodmap -

cat -- \
    "$xset_dir/*" \
    "$xset_dir/$km" \
    2> /dev/null \
    | tr '[:space:]' '\0' \
    | xargs -r0 xset

[ -x "$post_exec_dir/*" ] && "$post_exec_dir/*"
[ -x "$post_exec_dir/$km" ] && "$post_exec_dir/$km"
