#!/usr/bin/env sh

. shellverbose.sh
. utility.sh

mark="$1"

while IFS=" " read -r key val; do
    [ "$key" = "$mark" ] && {
        val="$(expandpath -- "$val")"

        [ ! -e "$val" ] && std_logerrq "Mark has an invalid value: $val\n"

        if [ -d "$val" ]; then
            printf "%s\n" "$val"
        else
            "$EDITOR" "$val" >&2
        fi

        exit 0
    }
done < "$(getpath -fu -- mrk)"

printf "Mark $mark does not exist.\n" >&2
exit 1
