#!/usr/bin/env sh

fzf --preview "printf '%s\n' {} | awk '{for (i=2; i<NF; i++) printf \$i \" \"; print \$NF}' | expandpath | xargs -d '\n' ls --color=always --" < "$(getflunsafe mrk)" | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}' | expandpath
