#!/usr/bin/env sh
# TODO: Include "$(getfl fls)". If the selection is a file, print its directory.

fzf --preview "printf '%s\n' {}
                   | awk '{for (i=2; i<NF; i++) printf \$i \" \"; print \$NF}'
                   | expandpath
                   | xargs -d '\n' ls --color=always
    " < "$(getfl loc)"
    | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}'
    | expandpath
