#!/usr/bin/env sh

eval "$(evalverbose)"

fzf --preview "printf '%s\n' {} \
                   | awk '{for (i=2; i<NF; i++) printf \$i \" \"; print \$NF}' \
                   | expandpath \
                   | xargs -d '\n' bat -p --color=always --
    " < "$(getpath -f -- fls)" \
    | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}' \
    | expandpath \
    | xargs -rod '\n' "$EDITOR"
