#!/usr/bin/env sh
# Select a file using fzf and open them in "$EDITOR".

eval "$(evalverbose)"

main() {
    fl="$(
        find . -type f -not -path "*/.git/*" -printf "%P\n" \
            | fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}' \
                  --preview-window 'right,60%,wrap'
    )" && [ -n "$fl" ] || exit 0
    (cd -- "$(dirname -- "$fl")" && "$EDITOR" -- "$(basename "$fl")")
}

[ "$#" -eq 0 ] && while true; do
    main
done

for i; do
    [ -d "$i" ] || {
        printf "Directory [%s] does not exist, exiting.\n" "$i"
        exit 1
    }
done

rootpwd="$PWD"
while true; do
    for i; do
        cd "$i" || exit 1
        main
        cd "$rootpwd" || exit 1
    done
done
