#!/usr/bin/env sh
# Select a file using fzf and open them in "$EDITOR".

main() {
    fl="$(
        find . -type f -not -path "*/.git/*" -printf "%P\n" \
            | fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}' \
                  --preview-window 'right,60%,wrap'
    )" || exit $?
    [ -n "$fl" ] && "$EDITOR" -- "$fl"
}

[ "$#" -eq 0 ] && while true; do
    main
done

while true; do
    for i; do
        [ ! -d "$i" ] && {
            printf "Directory [%s] does not exist, exiting.\n" "$i"
            exit 1
        }
        cd "$i" && main && cd .. || exit 1
    done
done
