#!/usr/bin/env sh
# Get directories with given codes.

set -e
item="${XDG_CONFIG_HOME:-"$HOME/.config"}/scripts/pathfinding/directories-container/$1"
[ -s "$item" ]
loc="$(cat -- "$item")"
printf "%s\n" "$loc"
