#!/usr/bin/env sh
# Get directories or the directories of files with given codes.

for i; do
    loc="$(getdir "$i")" || {
        loc="$(getfl "$i")" || continue
        loc="${loc%/*}"
    }
    printf "%s\n" "$loc"
done
