#!/usr/bin/env sh
# Get directories or the directories of files with given codes.

. evalverbose.sh

for i; do
    loc="$(getpath -du -- "$i" 2> /dev/null)" || {
        loc="$(getpath -fu -- "$i" 2> /dev/null)" || continue
        loc="${loc%/*}"
    }
    printf "%s\n" "$loc"
done
