#!/usr/bin/env sh
# Get directories with given codes.

set -e
item="$HOME/documents/sys-admin/locations-container/${1:?}"
[ -s "$item" ]
dir="$(cat -- "$item")"
[ -d "$dir" ] || mkdir -p -- "$dir"
printf "%s\n" "$dir"
