#!/usr/bin/env sh
# Get a file with the given code.

set -e
item="${XDG_CONFIG_HOME:-"$HOME/.config"}/scripts/pathfinding/files-container/${1:?}"
[ -s "$item" ]
fl="$(cat -- "$item")"
fldir="${fl%/*}"
[ -d "$fldir" ] || mkdir -p -- "$fldir"
printf "%s\n" "$fl"
