#!/usr/bin/env sh
# Get a file with the given code.

set -e
item="$HOME/documents/sys-admin/files-container/${1:?}"
[ -s "$item" ]
fl="$(cat -- "$item")"
fldir="${fl%/*}"
mkdir -p -- "$fldir"
touch -- "$fl"
printf "%s\n" "$fl"
