#!/usr/bin/env sh
# Usage: mvloc location file1 ... fileN
# Equivalent to: mv file1 ... fileN "$(getpath -ds -- location)"

dir="$(getpath -ds -- "$1")" || {
    printf "[ERROR]: getpath -ds -- failed, aborting.\n"
    exit 1
}

shift
set -- "$@" "$dir"
mv -n -- "$@"
