#!/usr/bin/env sh
# Usage: mvloc location file1 ... fileN
# Equivalent to: mv file1 ... fileN "$(getpath -ds -- location)"

eval "$(evalverbose)"

eval "$(getpath -dse -- "$1" dir 1 "[ERROR]: getpath -ds -- failed, aborting.")"

shift
set -- "$@" "$dir"
mv -n -- "$@"
