#!/usr/bin/env sh

locfl="${XDG_CONFIG_HOME:-"$HOME/.config"}/scripts/pathfinding/directories"
sort -o "$locfl" -- "$locfl"
container="$locfl-container"
rm -rf -- "$container"
mkdir -p -- "$container"

while IFS=" " read -r i j; do
    contains "$i" / && {
        printf "Keycode cannot contain /, aborting.\n"
        exit 1
    }
    
    printf "%s\n" "$j" | wordexp > "$container/$i"
done < "$locfl"
