#!/usr/bin/env sh

logerr() {
    printf "%s: %s\n" "${0##*/}" "$1" >&2
}

locfl="${XDG_CONFIG_HOME:-"$HOME/.config"}/scripts/pathfinding/directories"
sort -o "$locfl" -- "$locfl"
container="$locfl-container"
rm -rf -- "$container"
mkdir -p -- "$container"

cd "$container" || {
    logerr "could not cd into container: $container"
    exit 1
}
while IFS=" " read -r key val; do
    suffixes "$key" / && {
        logerr "key ends with /: $key"
        continue
    }
    [ -e "$key" ] && {
        logerr "key is duplicate: $key"
        continue
    }
    mkparent "$key"
    # substitution must be after wordexp
    printf "%s\n" "$val" | wordexp | sed -e 's|/\+|/|g' -e 's|/$||' | perl -p -e 'chomp if eof' > "$key"
done < "$locfl"
