#!/usr/bin/env sh

logerr() {
    printf "%s: %s\n" "${0##*/}" "$1" >&2
}

flsfl="${XDG_CONFIG_HOME:-"$HOME/.config"}/scripts/pathfinding/files"
container="$flsfl-container"
rm -rf -- "$container"
mkdir -p -- "$container"

cd "$container" || {
    logerr "could not cd into container: $container"
    exit 1
}
grep -vE -- "^(\s*#|$)" "$locfl" | while IFS=" " read -r key val; do
    suffixes "$key" / && {
        logerr "key ends with /: $key"
        continue
    }
    [ -e "$key" ] && {
        logerr "key is duplicate: $key"
        continue
    }
    mkparent "$key"
    printf "%s\n" "$val" | wordexp | perl -p -e 'chomp if eof' > "$key"
done
