#!/usr/bin/env sh

. shellverbose.sh

. io.sh

headsetcontrol > /dev/null || {
    readstr
    exit 1
}

while :; do
    case "$(std_read_char_tty)" in
        b) headsetcontrol -b;;
        i) printf "Value (i): " >&2; headsetcontrol -i "$(readstr)";;
        m) headsetcontrol -m;;
        q) exit 0;;
        s) printf "Value (s): " >&2; tglsidetone "$(readstr)";;
        *) printf "b: battery\ni: inactive time\nm: mix level\nq: quit\ns: sidetone level\n";;
    esac
done | grep -vE --line-buffered "^(Found |$)"
