#!/usr/bin/env sh
# Refresh documents. Designed to be used with cron.

. shellverbose.sh

while IFS=\; read -r evaldir dir cmd; do
    [ "$(printf "%s" "$evaldir" | cut -c1)" = "#" ] && continue

    [ "$evaldir" = "1" ] && dir="$(eval "$dir")"

    cd "$dir" || {
        printf "Could not cd to %s, continuing.\n" "$dir"
        continue
    }

    eval "$cmd"
done < "$(getpath -f -- refdoc)"
