#!/usr/bin/env sh

. config.sh
. execinfo.sh
. io.sh
. meta.sh
. shellverbose.sh

idvec() {
    # shellcheck disable=SC2154
    std::vector "$execname" "seenids" "$@"
}

kmmap() {
    std::unordered_map "$execname" "kms" "$@"
}

setkm() {
    printf "%s\n" "keymap: $1" >&2
    setxkbmap "$1"
    setxkb "$1"
}

# shellcheck disable=SC2154
configfl="$std_config_home/config.sh"
[ -f "$configfl" ] && . "$configfl"

std_ensure_defined \
    pre_query \
    post_query \
    first_time_setup \
    pre_update \
    post_update

idvec new
kmmap new

oldid="$(bspc query -n focused -N)"
bspc subscribe node_focus | while IFS=" " read -r _ _ _ ID; do
    xclassname="$(xclassname "$ID")"
    std_logerrraw "$xclassname" "FROM='$oldid'" "TO='$ID'"
    [ -z "$xclassname" ] && continue
    eval "$xclassname" # defines CLASS, INSTANCE and NAME

    pre_query
    KEYMAP="$(xkb-switch)"
    post_query
    kmmap "$oldid" = "$KEYMAP"

    if ! idvec -q find "$ID"; then
        first_time_setup
        idvec push_back "$ID"
    else
        pre_update
        setkm "$(kmmap "$ID")"
        post_update
    fi

    oldid="$ID"

    std_logerrraw ""
done
