#!/usr/bin/env sh

. shellverbose.sh

while :; do
    i=-1
    while [ "$((i += 1))" -lt "${2:-"3"}" ]; do
        mpv -no-config -- "${3:-"/usr/share/sounds/freedesktop/stereo/dialog-warning.oga"}"
    done
    sleep "${1:-7.5m}"
done
