#!/usr/bin/env sh
# For this script to have any effect, this fork must be used:
# https://github.com/XPhyro/st-xphyro

. shellverbose.sh

{ [ -z "$TABBED_XID" ] \
    || [ -z "$REUSE_TABBED_XID" ] \
    || [ "$REUSE_TABBED_XID" -le 0 ] 2> /dev/null; } && {
    TABBED_XID="$(tabbed -c -d $TABBED_ARGS)"
    export TABBED_XID
}
[ -z "$TABBED_XID" ] && execaux "$0" "$@"
exec execaux "$0" -w "$TABBED_XID" "$@"
