#!/usr/bin/env sh
# For this script to have any effect, this fork must be used:
# https://github.com/XPhyro/st-xphyro

. std.sh

[ -z "$TABBED_XID" ] \
    || [ -z "$REUSE_TABBED_XID" ] \
    || [ "$REUSE_TABBED_XID" -le 0 ] 2> /dev/null \
    && {
        TABBED_XID="$(tabbed -c -d $TABBED_ARGS)"
        export TABBED_XID
    }

if [ -z "$TABBED_XID" ]; then
    exec execaux "$0" "$@"
else
    exec execaux "$0" -w "$TABBED_XID" "$@"
fi
