#!/usr/bin/env sh
# Log the current brightness, then set it to 0 if it is not 0 else set it
# to the previously logged value. This only affects the laptop screen on my system.

eval "$(evalverbose)"

eval "$(getpath -fe -- brtcch fl 1 "[ERROR]: getpath -f -- failed, aborting.")"

# shellcheck disable=SC2154
val="$(cat -- "$fl")"

if [ "$val" = "0" ]; then
    val="$(brightnessctl g)"
    sudo brightnessctl s 0
else
    sudo brightnessctl s "$val"
    val="0"
fi

printf "%s" "$val" > "$fl"
