#!/usr/bin/env sh
# Set the brightness of the screen(s?). This only affects the laptop screen on my system.

eval "$(evalverbose)"

execmenu -p "Enter brightness %:" < /dev/null \
    | sed -e 's/\..*//g' -e 's/[^[:digit:]].*//g' \
    | xargs -d '\n' -rI '{}' sudo brightnessctl s '{}%'
