#!/usr/bin/env sh
# Disconnect from a bluetooth device. Prompts a selection if more than
# one device is connected or if the only device connected is a keyboard.

eval "$(evalverbose)"

devs="$(
    bluetoothctl paired-devices | while read -r _ i devname; do
        [ "$(
            qdbus --system org.bluez "/org/bluez/hci0/dev_$(
                printf "%s\n" "$i" | tr ':' '_'
            )" org.bluez.Device1.Connected
        )" = "true" ] && printf "%s %s\n" "$i" "$devname"
    done | sort
)"

[ -z "$devs" ] && {
    printf "No connected device, exiting.\n"
    exit 0
}

if [ "$(printf "%s\n" "$devs" | wc -l)" = 1 ] \
    && ! bluetoothctl info "${devs%%" "*}" | grep -iFq "keyboard"; then
    seldev="$devs"
else
    seldev="$(printf "%s\n" "$devs" | execmenu -i -p "Device to disconnect:")"
fi

[ -z "$seldev" ] && exit 0

seldevname="${seldev#*" "}"
seldevid="${seldev%%" "*}"

if bluetoothctl disconnect "$seldevid"; then
    notify-send -t 1000 "✔  $seldevname" "Device disconnected."
else
    notify-send -t 1000 "❌ $seldevname" "Could not disconnect device."
fi
