#!/usr/bin/env sh
# List clipped text logged by clplog and copy a selected one using dmenu.
# This script and clplog assume that the copied string does not contain the character .

sel="$(perl -0777 -pe 's/### END CLIP ###\n: [0-9]{10};\n### BEGIN CLIP ###\n//g;' -- "$(getfl clplog)" | tail -n +3 | head -n -1 | rofiseltail rofi -dmenu -i -l 8 -p "yank:")"

[ -n "$sel" ] && {
    lckget clplog
    printf "%s\n" "$sel" | tr '' '\n' | xclip -se c
}
