#!/usr/bin/env sh

. shellverbose.sh

tglapp -sk clpprint && {
    tglapp -kT clpprint off
    exit 0
}

clp="$(xclip -o -se c 2> /dev/null)"
l="$(printf "%s\n" "$clp" | wc -l)"
[ "$l" -eq 0 ] && exit 0

: $((l += 1))

printf "%s\n" "$clp" | tglapp -fkT clpprint on -- \
                              osd_cat -p middle -A center \
                                      -f "-*-helvetica-bold-r-*-*-*-180-*-*-*-*-*-*" \
                                      -c white -O 1 -u black -d 0 -l "$l"
