#!/usr/bin/env sh

loc="$(getdir dic)" || {
    printf "[ERROR]: getdir failed, aborting.\n"
    exit 1
}

menu="$(getmenu)"

lang="$(find "$loc" -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | sort | $menu -i)"
[ -n "$lang" ] || exit 1
ft="$(printf "dictionary\nthesaurus\n" | $menu -i)"
[ -n "$ft" ] || exit 1

# TODO: Force $menu to be non-fuzzy if it is rofi.
# TODO: Should the output be copied to the system clipboard?
$menu -i -snp -l 20 < "$loc/$lang/$ft" > /dev/null 2>&1
