#!/usr/bin/env sh

eval "$(evalverbose)"

eval "$(getpath -de -- dic dir 1 "[ERROR]: getpath -d -- failed, aborting.")"

menu="$(getmenu)"

# shellcheck disable=SC2154
lang="$(find "$dir" -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | sort | $menu -i)"
[ -n "$lang" ] || exit 1
ft="$(printf "dictionary\nthesaurus\n" | $menu -i)"
[ -n "$ft" ] || exit 1

# TODO: Should the output be copied to the system clipboard?
$menu -i -m normal -l 20 < "$dir/$lang/$ft" > /dev/null 2>&1
