#!/usr/bin/env sh
# Kill all processes named the selected string.

eval "$(evalverbose)"

ps -A --sort=-pcpu \
    | awk '{print $4}' \
    | uniqs \
    | execmenu -i -p 'Which process to kill?' \
    | xargs -d '\n' -r killall
