#!/usr/bin/env sh
# Toggle X keymap.

. evalverbose.sh

setkm() {
    setxkbmap "$1"
    setxkb "$1"
}

km="$(xkb-switch)"
setkm "$(printf "%s\n" "$km" | END= DEF=gb fmaps ${KMCYCLE_MAPPINGS:-gb=tr})"
