#!/usr/bin/env sh
# Choose a manual, generate its PDF and open it with zathura.

eval "$(evalverbose)"

apropos '' \
    | MENUARGS="-m prefix -l 20" execmenu \
    | head -n 1 \
    | sed -E 's/^(.* )\((.*)\)(\s+-\s+.*)?$/\2 \1/' \
    | xargs -d ' ' -rn 2 man -Tpdf \
    | xins -Rs -- zathura -
