#!/usr/bin/env sh
# xph-open assignments.

eval "$(evalverbose)"

eval "$(getpath -de -- ass dir 1 "[ERROR]: getpath -d -- failed, aborting.")"
# shellcheck disable=SC2154
find -L "$dir" -mindepth 1 -type f -printf "%T@;%p\n" \
    | sort -nr \
    | sed 's/^[0-9]*\.[0-9]*;//' \
    | while IFS= read -r i; do
        xph-open "$i" &
        sleep 0.1
    done
