#!/usr/bin/env sh
# xph-open assignments.

eval "$(evalverbose)"

loc="$(getpath -d -- ass)" || {
    printf "[ERROR]: getpath -d -- failed, aborting.\n"
    exit 1
}
find -L "$loc" -mindepth 1 -type f -printf "%T@;%p\n" \
    | sort -nr \
    | sed 's/^[0-9]*\.[0-9]*;//' \
    | while IFS= read -r i; do
        xph-open "$i" &
        sleep 0.1
    done
