#!/usr/bin/env sh

. evalverbose.sh

eval "$(getpath -fe -- zoom fl 1 "[ERROR]: getpath -f -- failed, aborting.")"

n=1
# shellcheck disable=SC2154
while IFS= read -r i; do
    [ -z "${i%%"#"*}" ] && continue

    lst="$lst$n - $(printf "%s" "$i" | awk -F '' '{print $1,"-",$2}')
"
    table="$table
$n$(printf "%s" "$i" | awk -F '' '{print $3}')"

    n=$((n + 1))
done < "$fl" 

sel="$(printf "%s" "$lst" | execmenu -i -l 20)"

[ -n "$sel" ] || exit 0

url="$(printf "%s" "$table" | grep "^$(printf "%s" "$sel" | awk '{print $1}')" | awk -F '' '{print $2}')"
$([ "$(printf "%s" "$url" | sed 's,://.*$,,')" = "zoommtg" ] && printf "firejail") xdg-open "$url"
