#!/usr/bin/env sh

loc="$(getdirsafe popupnote)" || {
    printf "[ERROR]: getdirsafe failed, aborting.\n"
    exit 1
}

find "$loc" -mindepth 1 -maxdepth 1 -printf "%P\n" \
    | execmenu -i -l 20 -p "popupnote:" \
    | xargs -d '\n' -rI '{}' xph-open "$loc/{}"
