#!/usr/bin/env sh

eval "$(evalverbose)"

eval "$(getpath -dse -- popupnote dir 1 "[ERROR]: getpath -ds -- failed, aborting.")"

find "$dir" -mindepth 1 -maxdepth 1 -printf "%P\n" \
    | execmenu -i -l 20 -p "popupnote:" \
    | xargs -d '\n' -rI '{}' xph-open "$dir/{}"
