#!/usr/bin/env sh
# Take and manage notes with dmenu.
# Designed to work as a scratchpad to dwm with st.

dir="$HOME/documents/notes/scratchpad"

files="$(find "$dir" -type f -printf "%f\n" | sort -rV)"
newfile="$(printf "%s" "$files" | head -n 1 | sed 's/_.*//')"
[ -z "$newfile" ] && newfile=-1

: $((newfile += 1))
newfile="$newfile"_"$(date +"%Y-%m-%d_%H-%M-%S")"

menu="$(getmenu)"
file="$(printf "%s\n%s" "$newfile" "$files" | $menu -i)"

[ -z "$file" ] && exit 0

if ! [ "$file" = "$newfile" ] && ! printf "%s" "$files" | grep -Fxq "$file"; then
    printf "%s" "$file" > "$dir/${newfile}_$(printf "%s\n" "" | $menu -p "Title for \"$dir/$newfile\":")"
    exit 0
fi

[ "$file" = "$newfile" ] && isnew=1

if [ "$isnew" = "1" ]; then
    vimcmd='startinsert'
else
    vimcmd='norm G$'
fi

path="$dir/$file"

vim -c "se ft=config | filetype detect | $vimcmd" -- "$path"

[ "$isnew" = "1" ] && {
    [ -f "$path" ] && title="$(printf "" | $menu -p "Title for \"$path\":")"
    [ -n "$title" ] && mv -- "$path" "${path}_$title"
}
