#!/usr/bin/env sh

. shellverbose.sh

menu="$(getmenu)"
se="$($menu -i -l 20 -p "search engine:" < "$(getpath -f -- search)" | awk -F, '{print $NF}')"
[ -n "$se" ] && printf "%s\n" "$se" | sed "s/%s/$(
    $menu -l 0 -p "search term:" < /dev/null | tr -d '\n' | jq -sRr @uri
)/g" | xargs -d '\n' -rn 1 xdg-open
