#!/usr/bin/env sh

eval "$(evalverbose)"

eval "$(getpath -fe -- sptkeys fl 1 "[ERROR]: getpath -f -- failed, aborting.")"

data="$(cat -- "$fl")"
long1="$(
    printf "%s\n" "$data" \
        | awk -F '' '{print $1}' \
        | awk 'length > max_length { max_length = length; longest_line = $0 } END { print max_length }')"
long2="$(
    printf "%s\n" "$data" \
        | awk -F '' '{print $2}' \
        | awk 'length > max_length { max_length = length; longest_line = $0 } END { print max_length }'
)"
long3="$(
    printf "%s\n" "$data" \
        | awk -F '' '{print $3}' \
        | awk 'length > max_length { max_length = length; longest_line = $0 } END { print max_length }'
)"

tmpfl="$(mktemp)"
sep="      "

printf "%s\n" "$data" | while IFS='' read -r i j k
do
    printf "%-${long1}s$sep%-${long2}s$sep%-${long3}s\n" "$i" "$j" "$k"
done | sed '2i\ ' > "$tmpfl"

"$PAGER" "$tmpfl"
