#!/usr/bin/env sh
# Cycle touchpad status.

. evalverbose.sh

tpid="$(xinput --list | grep -o 'Touchpad\s\+.*id=[0-9]\+' | grep -o '[0-9]\+$')"
xinput "$(
    xinput --list-props "$tpid" \
        | head -n 2 \
        | tail -n 1 \
        | awk '{print $4}' \
        | END= fmaps 1=--disable 0=--enable
)" "$tpid"
