#!/usr/bin/env sh
# Show weather forecast.
# Designed to work as a scratchpad for dwm with st.

v1="$(mktemp)"
v2="$(mktemp)"
curl v1.wttr.in/"$WTTR_LOCATION" 2> /dev/null | head -n -2 > "$v1"
curl v2.wttr.in/"$WTTR_LOCATION" 2> /dev/null | head -n -2 > "$v2"
paste -- "$v1" "$v2"
readchar > /dev/null
