#!/usr/bin/env sh

eval "$(evalverbose)"

eval "$(getpath -fe -- xdgopenlog logfl 1 "[ERROR]: getpath -f -- failed, aborting.")"

sel="$(
    awk -F ';' '{$1=strftime("%a %Y-%m-%d %H:%M:%S;", $1); print $0}' "$logfl" \
        | rofiseltail rofi -l 20 -p 'xdg-reopen:'
)"

[ -z "$sel" ] && exit 0

lckget xdgopenlog
exec xdg-open "${sel#*;  }"
