#!/usr/bin/env sh

eval "$(evalverbose)"

lck -rq clplog

execmenu < "$(getpath -f -- ynk)" | awk -F ";" '{print $2}' | sed 's/^ //' | tr -d '\n' | xclip -se c

# in case clplog is not running
sleep 5
lck -uq clplog
