#!/usr/bin/env sh
# Get the directories of files with given codes.

fls="$HOME/documents/sys-admin/files"

for i; do
    dirname -- "$(expandpath "$(printf "%s\n" "$(grep -E "^$i\s+.*" -- "$fls" | awk '{print $2}')")")"
done
