#!/usr/bin/env zsh
# A very slow script to fix symlinks
# Execute from the path ~/data
# Give arguments old-dir new-dir
# Ex: [xphyro@archlinux ~/data]$ ./fix-syms ig-favourite ig-fav

links="$(find "$1" -mindepth 1 -maxdepth 1 -type l -printf "%f\n")"
imgs="$(echo $links | grep -E "jpg|mp4")"
dirs="$(echo $links | grep -Ev "jpg|mp4")"

echo "$imgs" | while read -r i
do
    file="$( find ig -type f -name "$i" | head -n 1)"
    echo $file
    ln -s "$HOME/data/$file" "$HOME/data/$2/$i"
done

echo "$dirs" | while read -r i
do
    file="$( find ig -type d -name "$i" | head -n 1)"
    echo $file
    ln -s "$HOME/data/$file" "$HOME/data/$2/$i"
done
