#!/usr/bin/env sh

trap ctrl_c INT

ctrl_c() {
    [ "$newfollow1" ] && [ -f "$newfollow1" ] && rm "$newfollow1"
    [ "$newfollow2" ] && [ -f "$newfollow2" ] && rm "$newfollow2"
    exit 0
}

scrape() {
    instagram-scraper "@$1" -f "$2" -T '{username}_{year}-{month}-{day}_{h}-{m}-{s}_{urlname}_{shortcode}' --profile-metadata --media-metadata --latest --retry-forever
}

cdsafe() {
    cd "$1" || {
        echo "Could not cd to $1, exiting."
        exit
    }
}

cdsafe "$( getloc igg )"

newfollow1="$( dupe follow )"
sed -r -e '/^#/d' -e '/^$/d' -e 's/\s+.*$//' -i "$newfollow1"
if [ "$1" = "-r" ]
then
    sort -r -o "$newfollow1" "$newfollow1"
elif ! [ "$1" = "-n" ]
then
    sort -o "$newfollow1" "$newfollow1"
fi

newfollow2="$( dupe "$newfollow1" )"

LC_ALL=C sed -i '/^[v-zV-Z].*/d' "$newfollow1"
LC_ALL=C sed -i '/^[a-uA-U].*/d' "$newfollow2"

scrape args "$newfollow1"
scrape args_ "$newfollow2"

[ -f "$newfollow1" ] && rm "$newfollow1"
[ -f "$newfollow2" ] && rm "$newfollow2"

igdirs="$(find . -mindepth 1 -maxdepth 1 -type d -printf '%P\n' )"
printf "%s" "$igdirs" | while read -r i
do
    cdsafe "$i"
    find . -name "*.jpg" -or -name "*.mp4" -or -name "*.part" -printf '%P\n' | sort -n > ig.list
    cdsafe ..
done

cdsafe ..
cat .gitignore.def > .gitignore
echo >> .gitignore
find . -type l -printf '!%P\n' >> .gitignore
