#!/usr/bin/env sh
# Scrape profile photos of instagram accounts. First igscr should be run to generate JSON files.

base="$( getloc igg )"
log="igscrpp.log"

cd "$base" || exit

touch "$log"

jsons="$( find . -type f -name "*json" -printf '%P\n' | sort )"

for i in $jsons
do
    links="$( grep '"profile_pic_url"' "$i" | sed -e 's/"http/\nhttp/g' -e 's/",\s*$//' | grep ^http | uniq | grep scontent )"
    
    usr="$( echo "$i" | sed 's/\/.*//' )"

    for j in $links
    do
        name="$( echo "$j" | sed -e 's/.*\(\/.*jpg\).*/\1/' -e 's/\///' )"
        path="$usr/${usr}_1970-01-01_00h-00m-00s_$name"
        [ -f "$path" ] && continue 
        echo "$path" "$j" >> "$log"
        wget -O "$path" "$j" -U "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" || [ -f "$path" ] && rm "$path"
        [ -f "$path" ] && [ "$( du "$path" | awk '{print $1}' )" = "0" ] && rm "$path"
    done
done

#sed -e 's/"$//' "$log" | sort | uniq | sponge "$log"
vim "$log" -c '%s/"$' -c "sort u" -c wq # I want _ to have precedence over a
