#!/usr/bin/env sh
#
# Replace USERNAME with your username in the following unit file and copy it to
# ~/.config/systemd/user/warnbattery.service.
#
##
# [Unit]
# Description=When battery is low, play audio and send notification.
# Wants=sound.target
# After=sound.target
# After=graphical.target
# 
# [Service]
# Type=simple
# Restart=always
# RestartSec=180
# ExecStart=/usr/local/bin/warnbattery
# Environment=PATH=/usr/bin:/usr/local/bin
# Environment=GETPATH_CONFIG_HOME=/home/USERNAME/.config
# Environment=DISPLAY=:0
# Environment=WARNBATTERY_LOW_THRESHOLD=20
# Environment=WARNBATTERY_CRITICAL_THRESHOLD=10
# Environment=WARNBATTERY_UPDATE_PERIOD=90
# 
# [Install]
# WantedBy=default.target
##

getcapacity() {
    cat "$battery/capacity"
}

ischarging() {
    [ "$(cat "$battery/status")" = "Charging" ] && return 0
    return 1
}

warn() {
    prio="$1"
    # shellcheck disable=SC2154
    warndir="$confdir/$prio"
    warnfl="$(find "$warndir" -type f -print0 | shuf -z -n 1 | tr '\0' '\n')"
    play -- "$warnfl" 2> /dev/null
    [ -n "$DISPLAY" ] \
        && notify-send \
            -i "$(
                case "$1" in
                    low) printf battery-low;;
                    critical) printf battery-caution;;
                esac
            )" \
            -u critical \
            -t 0 \
            "$(printf "$1" | sed 's/.*/\u&/') Battery"
}

main() {
    ischarging && return

    capacity="$(getcapacity)"

    [ "$triggeredlow" -eq 1 ] \
        && [ "$capacity" -gt "$lowthresh" ] \
        && triggeredlow=0
    [ "$triggeredcritical" -eq 1 ] \
        && [ "$capacity" -gt "$critthresh" ] \
        && triggeredcritical=0

    [ "$triggeredlow" -eq 0 ] \
        && [ "$capacity" -le "$lowthresh" ] \
        && {
            warn low
            triggeredlow=1
            return
        }
    [ "$triggeredcritical" -eq 0 ] \
        && [ "$capacity" -le "$critthresh" ] \
        && {
            warn critical
            triggeredcritical=1
            return
        }
}

eval "$(evalverbose)"
eval "$(getpath -dse -- warnbattery confdir 1 "$0: getpath: config directory [warnbattery] is not configured")"

battery="${WARNBATTERY_BATTERY:-"$(find /sys/class/power_supply/ -mindepth 1 -maxdepth 1 -type l -print0 \
                                       | grep -z 'BAT[0-9]\+' \
                                       | sort -znr \
                                       | head -z -n 1 \
                                       | tr '\0' '\n')"}"
[ -z "$battery" ] && exit 1
lowthresh="${WARNBATTERY_LOW_THRESHOLD:-15}"
critthresh="${WARNBATTERY_CRITICAL_THRESHOLD:-7}"
period="${WARNBATTERY_UPDATE_PERIOD:-60}"
printf "%s=%s\n" \
    WARNBATTERY_LOW_THRESHOLD "$lowthresh" \
    WARNBATTERY_CRITICAL_THRESHOLD "$critthresh" \
    WARNBATTERY_UPDATE_PERIOD "$period"

triggeredlow=0
triggeredcritical=0
main
while true; do
    sleep "$period"
    main
done
