#!/usr/bin/env python3
# Generate lorem ipsum.


from sys import argv

from lorem import paragraph as lipsum


def main():
    print("\n\n".join([" ".join([lipsum() for _ in range(int(i))]) for i in argv[1:]]))


if __name__ == "__main__":
    main()
