#!/usr/bin/env python3
# Generate lorem ipsum.


import sys

from lorem import paragraph as lipsum


def main() -> int:
    print(
        "\n\n".join([" ".join([lipsum() for _ in range(int(i))]) for i in sys.argv[1:]])
    )

    return 0


if __name__ == "__main__":
    sys.exit(main())
