#!/usr/bin/env python3
# Generate lorem ipsum.


from sys import argv

from lorem import paragraph


def main():
    for i in argv[1:]:
        print(*[paragraph() for _ in range(int(i))])


if __name__ == "__main__":
    main()
