#!/usr/bin/env python3
# Generate cryptographically secure random bits and print them in hex.


from secrets import randbits
import sys


def main() -> int:
    for i in sys.argv[1:]:
        print(hex(randbits(int(i)))[2:])

    return 0


if __name__ == "__main__":
    sys.exit(main())
