#!/usr/bin/env python3
# Generate cryptographically secure random bits and print them in hex.


from secrets import randbits
from sys import argv


def main():
    for i in argv[1:]:
        print(hex(randbits(int(i)))[2:])


if __name__ == "__main__":
    main()
