#!/usr/bin/env sh

. std.sh

# TODO: svg preview does not work, fix.
# TODO: scope.sh does not handle on-demand files such as /proc/*. create a
#       scope script with support for these, a simpler API and without image
#       support (which is handled here).
# TODO: add support for CBR files.

exec_preview_image() {
    if [ -n "$DISPLAY" ]; then
        previewimage add "${id:-"$PPID"}" "$1" "$(($2 - 1))" "$(($3 - 1))" "$4" "$5"
        exit 1
    else
        chafa -s "$(($2 - 2))x$3" -- "$1"
        exit 0
    fi
}

scope() {
    "${XDG_CONFIG_HOME:-$HOME/.config}/ranger/scope.sh" \
        "$(realpath -P -- "$1")" \
        "$2" \
        "unused" \
        "$thumbfl" \
        "False"
}

main() {
    [ -d "$XDG_CACHE_HOME/lf/preview.lck" ] && {
        scope "$@"
        exit 1
    }

    # TODO: clean up thumbnail usage. perhaps lf-thumbnail should return the path to the thumbnail?
    lf-thumbnail "$1"

    realfl="$(realpath -P -- "$1")"
    thumbdir="${XDG_CACHE_HOME:-"$HOME/.cache"}/lf/thumbnails"
    mkdir -p -- "$thumbdir"
    thumbfl="$thumbdir/$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$realfl" | sha512sum | cut -d' ' -f1)"

    mime_type="$(file --mime-type --brief -- "$(realpath -P -- "$1")")"

    case "$mime_type" in
        text/html)
            case "$1" in
                *.[Mm][Dd]) mime_type=text/plain;;
            esac
            ;;
    esac

    case "$mime_type" in
        application/octet-stream)
            case "$1" in
                *.[Pp][Dd][Ff]) ;;
                *) scope "$@";;
            esac
            ;;
        application/epub+zip)
            exec_preview_image "$thumbfl" "$2" "$3" "$4" "$5"
            ;;
        application/pdf|image/heic|text/html)
            exec_preview_image "$thumbfl.jpg" "$2" "$3" "$4" "$5"
            ;;
        video/*)
            if [ -n "$KITTY_PID" ]; then
                exec_preview_image "$thumbfl.gif" "$2" "$3" "$4" "$5"
            else
                exec_preview_image "$@"
            fi
            ;;
        image/gif)
            if [ -n "$KITTY_PID" ]; then
                exec_preview_image "$@"
            else
                exec_preview_image "$thumbfl.jpg" "$2" "$3" "$4" "$5"
            fi
            ;;
        image/*)
            exec_preview_image "$@"
            ;;
        */xml|application/javascript|application/x-subrip)
            previewtext "$@"
            ;;
        text/plain)
            if [ -s "$thumbfl" ]; then
                exec_preview_image "$thumbfl" "$2" "$3" "$4" "$5"
            else
                if [ "$(stat --printf="%s" -- "$1")" -le 16777216 ]; then # 16MiB
                    scope "$@"
                else
                    cat -- "$1"
                fi
            fi
            ;;
        *)
            scope "$@"
            ;;
    esac
}

main "$@"
exit 0
