#!/usr/bin/env sh

mons="$(bspc query -M --names)"
firstmon="$(printf "%s\n" "$mons" | head -n 1)"
defsink="$(voldefsink)"
auxsink="$(volauxsink)"

bspc monitor "$firstmon" -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
MONITOR="$firstmon" DEFSINK="$defsink" AUXSINK="$auxsink" polybar --reload primary &

printf "%s\n" "$mons" | tail -n +2 | while IFS= read -r m; do
    bspc monitor "$m" -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
    MONITOR="$m" DEFSINK="$defsink" AUXSINK="$auxsink" polybar --reload auxiliary &
done

wait
