#!/usr/bin/env sh
# Kill all processes named the selected string.

ps -A --sort=-pcpu | awk '{print $4}' | uniqs | ${MENU:-$(fmapsb rofi='rofi -dmenu' dmenu='dmenu')} -i -p 'Which process to kill?' | xargs -d '\n' -r killall
