#!/usr/bin/env sh

loc="$(getdir popupnote)" || {
    printf "[ERROR]: getdir failed, aborting.\n"
    exit 1
}

find "$loc" -mindepth 1 -maxdepth 1 -printf "%P\n" | dmenu -i -l 20 -p "popupnote:" | xargs -d '\n' -rI '{}' xdg-open "$loc/{}"
