#!/usr/bin/env sh

tmp="$(mktemp)"
cp -f -- /dev/stdin "$tmp"
stdl="$(wc -l < "$tmp")"

tput smcup
tput civis
clear
terml="$(tput lines)"
[ "$terml" -gt "$stdl" ] && putsn "$(((terml - stdl) / 2))"
cat -- "$tmp"
