#!/usr/bin/env sh
# Choose a unicode character and copy it.
# Adapted from Luke Smith's voidrice.

chosen="$(cut -d ';' -f1 -- "${XDG_DATA_HOME:-"$HOME"}/code/rsrc/unicode/unicode-characters" | dmenu -i -l 20 | sed "s/ .*//")"
[ -z "$chosen" ] && exit 0
lckget clplog
printf "%s" "$chosen" | tr -d '\n' | xclip -se c
