#!/usr/bin/env sh

[ "$BSPWMPADINIT_VERBOSE" = 1 ] && set -x

lckdir="$1"
lck="$2"
shift 2

[ "$lck" != "0" ] && {
    printf "%s\n" "$$" > "$lckdir/$lck/pid"
    xdotool search --limit 0 --classname "bspwmpad$lck" | xargs -d '\n' printf "0x%X\n" > "$lckdir/$lck/ids"
    printf "%s - %s\n" "bspwmpad #$lck" "$(date +"%a %F %H:%M:%S")"

    if [ "$#" -eq 0 ]; then
        printf "%s\n\n" "Deploying shell: $SHELL"
        exec "$SHELL"
    else
        { printf "%s " "$@" | head -c -1; printf "\n"; } > "$lckdir/$lck/command"
        printf "%s\n\n" "Running command: $*"
        exec "$@"
    fi
}

while true; do
    pid="2147483647,$(find "$lckdir" -mindepth 2 -maxdepth 2 -name "pid" -exec cat {} \; | tr '\n' ',')"
    top -n 1 -p "${pid%?}"
    tput civis
    sleep 1
done
