#!/usr/bin/env sh
# Log notifications.
# Archived in favour of python-dbus to prevent ambiguous parsing of dbus-monitor.

fl="$(getfl notiflog)" || {
    printf "[ERROR]: getfl failed, aborting.\n"
    exit 1
}
lckfl="$(getfl notifloglck)" || {
    printf "[ERROR]: getfl failed, aborting.\n"
    exit 1
}
beg="##beg##"
end="##end##"

rm -f -- "$lckfl" 2> /dev/null

event=""
willreg=0

dbus-monitor "interface='org.freedesktop.Notifications', member='Notify'" | while IFS= read -r i; do
    [ "$willreg" = 1 ] && event="$event$i
"
    if contains "$i" "   uint32 "; then
        willreg=1
        continue
    elif ! contains "$i" "   int32 "; then
        continue
    fi

    [ -f "$lckfl" ] && {
        rm -f "$lckfl"
        event=""
        willreg=0
        continue
    }

    event="$(printf "%s" "$event" | sed '/^   array \[$/q' | head -n -1 | tail -n +2)"
    title="$(printf "%s\n" "$event" | head -n 1 | sed -E 's/   string "(.*)"$/\1/')"
    body="$(printf "%s\n" "$event" | tail -n +2 | sed -E -e '1s/   string "(.*)"?/\1/' -e '$s/"$//')"

    [ -z "$title" ] && [ -z "$body" ] && continue

    printf "%s\n%s\n%s\n%s\n%s\n" \
        "$beg" \
        "$(date +%s)" \
        "$title" \
        "$body" \
        "$end" >> "$fl"

    event=""
    willreg=0
done
