#!/usr/bin/env sh

printf "%s " -s \
    'XXXXXX' \
    'XXXXXX/YYYYYY' \
    '~' \
    '~/XXXXXX' \
    '~/XXXXXX/' \
    '~/XXXXXX/YYYYYY' \
    '~/XXXXXX//////YYYYYY' \
    '/home/XXXXXX' \
    '/home/XXXXXX/YYYYYY'
