#!/usr/bin/env sh

RED='\033[0;31m'
NC='\033[0m'

changed="$(git diff --cached --name-only)"

printf "%s\n" "$changed" \
    | grep -E "^src/c(pp)?/.*\.[ch](pp)?$" \
    | while IFS= read -r fl; do
        realfl="$PWD/$fl"
        [ -e "$realfl" ] || continue
        flcontent="$(cat -- "$realfl")"
        (cd "$(dirname -- "$realfl")" \
             && clang-format -i --style=file -- "$realfl" \
             && {
                 [ -z "$GIT_PRE_COMMIT_NO_ADD" ] \
                 || [ "$GIT_PRE_COMMIT_NO_ADD" -ne 0 ]
             } \
             && git add -- "$realfl"
        )
        printf "%s\n" "$flcontent" | cmp -s -- "$realfl" \
            && printf "Formatted file %s\n" "$(basename -- "$realfl")"
    done

printf "%s\n" "$changed" \
    | grep "^src/py/.*[^/]" \
    | while IFS= read -r fl; do
        [ ! -x "$fl" ] || {
            realfl="$PWD/$fl"
            [ -e "$realfl" ] || continue
            flcontent="$(cat -- "$realfl")"
            (cd "$(dirname -- "$realfl")" \
                 && black -- "$realfl" \
                 && {
                     [ -z "$GIT_PRE_COMMIT_NO_ADD" ] \
                     || [ "$GIT_PRE_COMMIT_NO_ADD" -ne 0 ]
                 } \
                 && git add -- "$realfl"
            )
            printf "%s\n" "$flcontent" | cmp -s -- "$realfl" \
                && printf "Formatted file %s\n" "$(basename -- "$realfl")"
        }
    done

year="$(date '+%Y')"
grep -Fq -- "2020-$year" LICENSE \
    || printf "$RED%s$NC\n" \
        "Please update the year in the license header."
