#!/usr/bin/env sh
# Use speedtest to test internet connection and log the results.
# speedtestlogp can be used to print the logs.

eval "$(evalverbose)"

ping -c 1 speedtest.net > /dev/null 2>&1 || {
    printf "%s\n" "Cannot reach speedtest.net servers, exiting."
    exit 1
}

printf "%s\n" "Testing..."

result="$( speedtest || {
    printf "%s\n" "Test failed, exiting."
    exit 1
} )"

log="$(
    date +%s
);$(
    printf "%s\n" "$result" | grep -F "Testing from" | sed -e 's/Testing from //' -e 's/\.\.\.//'
);$(
    printf "%s\n" "$result" | grep -F "Hosted by"    | sed -e 's/Hosted by //' -e 's/:.*//'
);$(
    printf "%s\n" "$result" | grep -F "Hosted by"    | awk '{print $(NF - 1)" "$NF}'
);$(
    printf "%s\n" "$result" | grep -F "Download:"    | awk '{print $2" "$3}'
);$(
    printf "%s\n" "$result" | grep -F "Upload:"      | awk '{print $2" "$3}'
)"

printf "\n%s\n" "$log" | sed 's/;/\n/g'
printf "\n\nLogging results...\n"

eval "$(getpath -fe -- stl fl 1 "[ERROR]: getpath -f -- failed, aborting.")"

printf "%s\n" "$log" >> "$fl"

printf "%s\n" "Done."
