#!/usr/bin/env sh
# Sync mail and notify if new mail exists.

eval "$(evalverbose)"

timefile="$HOME/.config/mutt/.syncmailtime"
maildir="$HOME/.local/share/mail"
accdir="$HOME/.config/mutt/accounts"

mbsync -a || {
    color red "could not sync mails"
    logerrnotif "$0" "$*" "ERROR" 'Could not sync mails' 'Run `mbsync -a -Dsmnd` to debug.'
    exit 1
}

find "$maildir" -mindepth 1 -maxdepth 1 -type d | while IFS= read -r i; do
    acc="$(printf "%s" "$i" | sed "s/.*\///")"
    count=$(
        find "$maildir/$acc" -ipath "$maildir/$acc/inbox/new/*" -type f -newer "$timefile" 2> /dev/null \
        | wc -l
    )
    [ "$count" -gt 0 ] \
        && notify-send -i mail-unread -u critical -t 0 "📬 syncmail [$count]" "[$count] new mail$(
            [ "$count" -gt 1 ] && printf "s"
        ) in $(
            grep "^set from" -- "$accdir/$acc.muttrc" \
                | tail -n 1 \
                | sed -E 's/set\s+from\s*=\s*"?(.*[^"])"?/\1/'
        )." &
done

notmuch new || color red "could not index mails"

touch -- "$timefile"
