#!/usr/bin/env sh
# Pull updates from git and compile programs. Used list file is the file coded upabl.

eval "$(evalverbose)"

cleanexit() {
    # shellcheck disable=SC2154
    rm -rf -- "$lckdir" 2> /dev/null
    exit 0
}

log() {
    printf "[update]: %s\n" "$1"
}

eval "$(getpath -due -- upabllck lckdir 1 "[ERROR]: getpath -du -- failed, aborting.")"
eval "$(getpath -fe  -- upabl    lst    1 "[ERROR]: getpath -f -- failed, aborting." )"

for i; do
    if [ "$i" = "-u" ] || [ "$i" = "--unlock" ]; then
        rm -rf -- "$lckdir" 2> /dev/null
        exit 0
    fi
done

log "Acquiring lock..."

trap cleanexit INT

lck "$lckdir"

# yay -Syu # --noconfirm

log "Reading updateables.
"

errcount=0
cmdcount=0

# shellcheck disable=SC2154
while IFS= read -r i; do
    [ "$(printf "%s" "$i" | sed -E 's/^\s*//' | cut -c1)" = "#" ] && continue

    loc="$(printf "%s" "$i" | awk -F "" '{print $1}')"
    cmd="$(printf "%s" "$i" | awk -F "" '{print $2}')"

    log "Parsing $loc."

    cd "$(getpath -ds -- "$loc")" || {
        log "Could not find location $loc."
        continue
    }

    log "Pulling updates."
    if [ "$(git pull | tail -n 1 | grep --color=never -o " up to date.$")" = " up to date." ]; then
        log "Already up to date."
    else
        eval "( $cmd )" || {
            log "Failed to update $loc."
            : $((err += 1))
        }
    fi

    : $((cmdcount += 1))

    printf "\n"
done < "$lst"

rm -rf -- "$lckdir"

log "Done."

exitcode=0
[ "$errcount" -ne 0 ] && : $((exitcode = cmdcount - errcount + 1))

exit "$exitcode"
