#ifndef HEADER_SCRIPTS_C_PARAMUTIL_
#define HEADER_SCRIPTS_C_PARAMUTIL_

#define STRINGIFY_INTERNAL(VAL) #VAL
#define STRINGIFY(VAL) STRINGIFY_INTERNAL(VAL)

#endif /* ifndef HEADER_SCRIPTS_C_PARAMUTIL_ */
