#ifndef HEADER_SCRIPTS_SYS_PARAMUTIL
#define HEADER_SCRIPTS_SYS_PARAMUTIL

#define STRINGIFY_INTERNAL(VAL) #VAL
#define STRINGIFY(VAL) STRINGIFY_INTERNAL(VAL)

#endif /* ifndef HEADER_SCRIPTS_SYS_PARAMUTIL */
