#!/usr/bin/env sh
# Change the volume of the secondary pulseaudio sink.

. shellverbose.sh

lck -rq volauxchdefset

sink="$(voldefsink)"
vol="$(volgetsinkraw "$sink")"
pactl set-sink-volume "$(volauxsink)" "$@"
pactl set-sink-volume "$sink" "$vol"

lck -uq volauxchdefset
