#!/usr/bin/env sh
# Change the volume of the secondary pulseaudio sink.

eval "$(evalverbose)"

lck -rq volauxchdefset

sink="$(voldefsink)"
vol="$(volgetsinkraw "$sink")"
pactl set-sink-volume "$(volauxsink)" "$@"
pactl set-sink-volume "$sink" "$vol"

ulck -uq volauxchdefset
