#!/usr/bin/env sh

. std.sh

if [ "$PAD" = "bspwmpad" ]; then
    extraopts="-g 768x1024"
else
    extraopts=
fi

"$PAD" $extraopts -t "${0##*/}" -- sh -c '
    . io.sh

    noconfirm=
    yesno -- "Pass \`--noconfirm?\`" && noconfirm="--noconfirm"
    printf "\n"

    update > /dev/null 2>&1 &
    if time -v yay -Syu $noconfirm; then
        [ -n "$YAY_ALWAYS_CLEAN_CACHE" ] \
            && [ "$YAY_ALWAYS_CLEAN_CACHE" -ne 0 ] \
            && yay -Scc --noconfirm > /dev/null 2>&1
    else
        color red "ERROR(s) encountered."
    fi
    flushterm
    jobs %% && printf "Waiting for [update].\n"
    wait
    color green "All done. Check for errors."
    std_wait_enter
'
