#!/usr/bin/env sh

set -e

[ -n "$POLYBAR" ] && [ "$POLYBAR" -ne 0 ] || . std.sh
{ [ -z "$-" ] || [ -n "${-%%*x*}" ] || { [ -n "$POLYBAR" ] && [ "$POLYBAR" -ne 0 ]; }; } && exec 2> /dev/null

eval "$(
    { headsetcontrol -b -m || sudo headsetcontrol -b -m; } 2> /dev/null \
        | grep -E '(Battery|Chat-Mix):\s+([0-9]+|Charging)' \
        | tr -d ' -' \
        | tr ':' '=' \
        | tr -d '%'
)"
[ -n "$Battery" ] && [ -n "$ChatMix" ] || exit 1

printf "🎧 🔋 %s 🎮 %s%% 🎤 %s%%" \
    "$(
        if [ "$Battery" != "Charging" ] && [ "$Battery" != "-1" ]; then
            printf "scale = 15; (%s - 7) * 1.075268817\n" "$Battery" \
                | bc \
                | cut -d'.' -f1 \
                | tr -d '\n'
            printf "%%"
        else
            printf "Charging"
        fi
    )" \
    "$(
        printf "scale = 15; (128 - %s) * 0.78125\n" "$ChatMix" \
            | bc \
            | cut -d'.' -f1
    )" \
    "$(
        printf "scale = 15; %s * 0.78125\n" "$(tglsidetone)" \
            | bc \
            | cut -d'.' -f1
    )"
