#!/usr/bin/env sh

killall "$1" && exit 0

case "$1"
in
    lmb) 
        sleep 2
        while true
        do
            xdotool click 1
            sleep 0.1
        done
        ;;
    x) 
        while true
        do
            xdotool type "$( dmenu -p "key sequence:" )"
            sleep 0.1
        done
        ;;
    *) exit 1;;
esac
