#!/usr/bin/env sh

eval "$(evalverbose)"

headsetcontrol > /dev/null || {
    readstr
    exit 1
}

while true; do
    case "$(readchar)" in
        s) printf "Value (s): " >&2; tglsidetone "$(readstr)";;
        b) headsetcontrol -b;;
        i) printf "Value (i): " >&2; headsetcontrol -i "$(readstr)";;
        m) headsetcontrol -m;;
        q) exit 0;;
        *) printf "Only s, b, i, m and q are supported.\n";;
    esac
done | grep -vE --line-buffered "^(Found |$)"
