#!/usr/bin/env sh

cfgdir="${XDG_CONFIG_HOME:-"$HOME/.config"}/headsetcontrol"
mkdir -p -- "$cfgdir"
fl="$cfgdir/sidetone"

[ "$#" -eq 0 ] && exec tr -d '\n' < "$fl"

case "$(cat -- "$fl")" in
    "$1") val=0;;
    *) val="$1";;
esac

headsetcontrol -s "$val" || {
    ec="$?"
    printf "%s" -2 > "$fl"
    exit "$ec"
}

printf "%s" "$val" > "$fl"
