#!/usr/bin/env sh

fl="${XDG_CACHE_HOME:-"$HOME/.cache"}/headsetcontrol/sidetone"

[ "$#" -eq 0 ] && exec tr -d '\n' < "$fl"

case "$(cat -- "$fl")" in
    "$1") val=0;;
    *) val="$1";;
esac

headsetcontrol -s "$val" || {
    ec="$?"
    truncate -s 0 -- "$fl"
    exit "$ec"
}

printf "%s\n" "$val" > "$fl"
