#!/usr/bin/env sh

eval "$(evalverbose)"

cfgdir="${XDG_CONFIG_HOME:-"$HOME/.config"}/scripts/headsetcontrol"
mkdir -p -- "$cfgdir"
stfl="$cfgdir/sidetone"

[ "$#" -eq 0 ] && exec tr -d '\n' < "$stfl"

case "$(cat -- "$stfl")" in
    "$1") val=0;;
    *) val="$1";;
esac

headsetcontrol -s "$val" || {
    ec="$?"
    printf "%s" -2 > "$stfl"
    exit "$ec"
}

printf "%s" "$val" > "$stfl"
