#!/usr/bin/env sh

preargs="${NSXIV_ARGS_PRE:-"-a -N nsxiv-env"}"
postargs="$NSXIV_ARGS_POST"

{
    printf "%s\0" $preargs
    for i; do
        if [ "$i" != "--" ]; then
            printf "%s\0" "$i"
        else
            printf "%s\0" $postargs --
        fi
    done
} | exec xargs -0 nsxiv
