#!/usr/bin/env python3


from datetime import datetime as dt
import argparse
import re
import sys


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("-e", "--exit-on-error", action="store_true")
    args = parser.parse_args()

    while True:
        try:
            i = input("Enter date: ")
        except (EOFError, KeyboardInterrupt):
            return 0

        s = re.sub(r"\s|[-/_|,.]", "", i)

        try:
            date = dt(int(s[:-4]), int(s[-4:-2]), int(s[-2:]))
        except ValueError:
            print("Input is invalid.")
            if args.exit_on_error:
                return 1
            continue

        now = dt.now()
        print(
            f"\tDate: {date}",
            f"\tNow: {now}",
            f"\tDifference: {date - now}",
            sep="\n",
            end="\n",
        )


if __name__ == "__main__":
    sys.exit(main())
