#!/usr/bin/env python3


from datetime import datetime as dt
import argparse
import re
import sys


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("-e", "--exit-on-error", action="store_true")
    args = parser.parse_args()

    while True:
        try:
            i = input("Enter date: ")
        except (EOFError, KeyboardInterrupt):
            return 0
        s = re.sub("\s|[-/_|,.]", "", i)
        try:
            date = dt(int(s[:-4]), int(s[-4:-2]), int(s[-2:]))
            now = dt.now()
            print(f"\tDate: {date}\n\tNow: {now}\n\tDifference: {date - now}\n")
        except:
            if args.exit_on_error:
                return 1
            print("Input is invalid.")


if __name__ == "__main__":
    sys.exit(main())
