#!/usr/bin/env sh

. shellverbose.sh

add() {
    pid="$1"
    file="$2"
    pane_width="$3"
    pane_height="$4"
    pane_x="$5"
    pane_y="$6"
    shift 6

    [ -e "$tmpdir/$pid" ] && {
        remove "$pid"
    }

    ueberzugpp layer --no-stdin --silent --use-escape-codes --pid-file "$tmpdir/$pid" < /dev/null > /dev/null
    ueberzugpp cmd \
        -s "$ueberzugpp_tmpdir/ueberzugpp-$(cat -- "$tmpdir/$pid").socket" \
        -a add \
        -i PREVIEW \
        -x "$pane_x" \
        -y "$pane_y" \
        --max-width "$pane_width" \
        --max-height "$pane_height" \
        -f "$file" < /dev/null > /dev/null

    [ "$#" -ne 0 ] && add "$@"
}

remove() {
    pid="$1"
    shift 1

    [ -e "$tmpdir/$pid" ] && {
        xargs -r kill -SIGKILL -- < "$tmpdir/$pid"
        rm -f -- "$tmpdir/$pid"
    }

    [ "$#" -ne 0 ] && remove "$@"
}

tmpdir="${TMPDIR:-/tmp}/previewimage"
mkdir -p -- "$tmpdir" || [ -d "$tmpdir" ] || exit 1

ueberzugpp_tmpdir="${TMPDIR:-/tmp}"

case "$1" in
    add) shift 1; add "$@";;
    remove) shift 1; remove "$@";;
    *) exit 1;;
esac
