#!/usr/bin/env sh

logfl="$(getfl xdgopenlog)" || {
    printf "[ERROR]: getfl failed, aborting.\n"
    exit 1
}

sel="$(awk -F ';' '{$1=strftime("%a %Y-%m-%d %H:%M:%S;", $1); print $0}' "$logfl" | dmenu -sel 200000000 -l 20 -p 'xdg-reopen:')"

[ -z "$sel" ] && exit 0

lckget xdgopenlog
exec xdg-open "${sel#*;  }"
