#!/usr/bin/env sh

. std.sh

eval "$(getpath -de -- dic dir 1 "[ERROR]: getpath -d -- failed, aborting.")"

menu="$(getmenu -i -m normal -l 20)"

# shellcheck disable=SC2154
lang="$(find "$dir" -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | sort | $menu -p "select language")"
[ -n "$lang" ] || exit 1
ft="$(printf "%s\n" "dictionary" "thesaurus" | $menu -p "select type")"
[ -n "$ft" ] || exit 1

sel="$($menu -p "select to copy" < "$dir/$lang/$ft")" \
    && [ -n "$sel" ] \
    && printf "%s" "$sel" | xclip -se c
