#!/usr/bin/env sh

. shellverbose.sh

# shellcheck disable=SC2046
xdotool mousemove $(
    xrandr --listactivemonitors \
        | grep ".*$(moncur)$" \
        | awk '{print $3}' \
        | tr -c 0-9 " " \
        | awk '{print ($1 + $5 - 23)" "($6 + 37)}'
) click 1 mousemove restore
