#!/usr/bin/env sh

. std.sh

apropos '' \
    | fzf --no-multi \
    | awk '{
        cmd = $1
        sec = substr($2, 2, length($2) - 2)
        printf("%s", sec "\0" cmd "\0")
    }' | xargs -r0 -n 2 man
