#!/usr/bin/env sh
# Prompt installed steam games and run the selected one.

. std.sh

grep -E '\s*"path"\s*".*"$' "$(getpath -f -- steamlibdirs)" | awk -F '"' '{print $4}' | while IFS= read -r i; do
    cd "$i/steamapps" || {
        printf "%s\n" "Could not cd into '$i/steamapps', passing."
        continue
    }

    find '.' -mindepth 1 -maxdepth 1 -type f -name "*.acf" -printf '%P\n' | while IFS= read -r j; do
        printf '%s\n' "$(
            grep '"appid"' -- "$j" | awk -F '"' '{print $4}'
        ) $(
            grep '"name"' -- "$j" | awk -F '"' '{print $4}'
        )"
    done
done | execmenu -i -l 25 -p "Select game:" \
     | awk '{print $1}' \
     | xargs -d '\n' -rI '{}' xdg-open 'steam://run/{}'
