#!/usr/bin/env sh
# A dmenu prompt to unmount drives. Drives included in /etc/fstab are excluded.

. std.sh

. execinfo.sh
. sudo.sh

send_notification() {
    std_sudo_env notify-send "$@"
}

assertroot || exit 1

drives="$(
    mountpoint -q -- "/mnt/iPhone" && printf "%s\n" "/mnt/iPhone"
    mntdrives="$(lsblk -nrpo "mountpoint,size" | grep "^[^[:space:]]" | LC_ALL=C sort -k 1n)"
    fstab="$(sed -e '/^\s*$/d' -e '/^\s*[#\/]/d' /etc/fstab | awk '{print $2}' | LC_ALL=C sort)"
    printf "%s\n" "$mntdrives" | while read -r i j; do
        [ "$i" = "${fstab%%"
"*}" ] && {
            fstab="${fstab#*"
"}"
            continue
        }

        printf "%s %s\n" "$i" "$j"
    done
)"

[ -z "$drives" ] && exit 1

chosen="$(printf "%s\n" "$drives" | execmenu -i -p "Unmount which drive?" | cut -d' ' -f1)"

[ -z "$chosen" ] && exit 1

if umount "$chosen"; then
    send_notification "$std_execname" "Successfully unmounted $chosen."
else
    send_notification "$std_execname" "Failed to unmount $chosen."
fi
