#!/usr/bin/env sh
# Choose a unicode character and copy it.

. std.sh

fl="${XDG_DATA_HOME:-"$HOME"}/code/rsrc/unicode/unicode-characters"
chosen="$(
    cut -d ';' -f1 -- "$fl" \
        | rofifit rofi -dmenu -i -font 'JetBrainsMono 16' -p 'yankunicode:' \
        | sed "s/ .*//"
)"
[ -z "$chosen" ] && exit 0
lck -rq clplog
printf "%s" "$chosen" | tr -d '\n' | xclip -se c
