#!/usr/bin/env sh
# Gives a dmenu prompt to automatically mount drives.

assertroot || exit 1

chosen="$(printf "%s\n" "$(lsblk -rpo "name,type,size,mountpoint" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')" | dmenu -i -p "Drive to mount:" | cut -d' ' -f1)"

[ -z "$chosen" ] && exit 1

mount "$chosen" 2>/dev/null && exit 0

label="$(lsblk -rpo "name,label" | grep -F "$chosen " | cut -d' ' -f2- | xargs -r -n 1 -d '\n' printf -- | awk '{print(tolower($0))}' | tr -d '[:blank:]/')"

mp="/mnt/${label:-"${chosen##*/}"}"

[ -z "$mp" ] && exit 1
[ -d "$mp" ] || mkdir -p -- "$mp"

mount -- "$chosen" "$mp"
