#!/bin/sh
# A dmenu prompt to unmount drives. Drives included in /etc/fstab are excluded.
# Adapted from Luke Smith's voidrice.

unmountusb() {
    [ -n "$drives" ] || exit 1

    chosen="$(printf "%s" "$drives" | dmenu -i -p "Unmount which drive?" | awk '{print $1}')"
    [ -n "$chosen" ] || exit 1

    sudo -A umount "$chosen" && notify-send "💻 Drive unmounting" "$chosen unmounted."
}

unmountandroid() {
    chosen="$(awk '/simple-mtpfs/ {print $2}' /etc/mtab | dmenu -i -p "Unmount which device?")"
    [ -n "$chosen" ] || exit 1

    sudo -A umount -l "$chosen" && notify-send "🤖 Android unmounting" "$chosen unmounted."
}

asktype() {
    case "$(printf "Drive\\nAndroid" | dmenu -i -p "Unmount a drive or Android device?")" in
        USB     ) unmountusb ;;
        Android ) unmountandroid ;;
        *       ) exit 0;;
    esac
}

drives="$(
    mntdrives="$(lsblk -nrpo "mountpoint,size" | grep "^[^[:space:]]" | LC_ALL=C sort -k 1n)"
    fstab="$(sed -e '/^\s*$/d' -e '/^\s*[#\/]/d' /etc/fstab | awk '{print $2}' | LC_ALL=C sort)"
    printf "%s\n" "$mntdrives" | while read -r i j; do
        [ "$i" = "${fstab%%"
"*}" ] && {
            fstab="${fstab#*"
"}"
            continue
        }

        printf "%s %s\n" "$i" "$j"
    done
)"

if ! grep simple-mtpfs /etc/mtab; then
    [ -z "$drives" ] && {
        printf "%s\n" "No drives to unmount."
        exit 0
    }
    unmountusb
elif [ -n "$drives" ]; then
    asktype
else
    unmountandroid
fi
