branches: master

pipeline:
  analyse:
    image: ubuntu:22.04
    commands: |
      apt-get -y update
      apt-get -y install make gcc g++ zlib1g-dev shellcheck clang clang-tidy clang-tools perl libfindbin-libs-perl
      make analyse
