branches: master

pipeline:
  build:
    image: ubuntu:22.04
    commands: |
      apt-get -y update
      apt-get -y install make git gcc g++ zlib1g-dev libmagic-dev moreutils libbsd-dev cargo libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev
      make install
      make test
