branches: master

pipeline:
  build:
    image: ubuntu:22.04
    commands: |
      apt-get -y update
      apt-get -y install make gcc g++ zlib1g-dev libmagic-dev moreutils
      make install
      make test
