#!/usr/bin/env sh

. shellverbose.sh

state="$(bspc config pointer_follows_focus | END= fmaps false=true true=false)"
bspc config pointer_follows_focus "$state"
bspc config pointer_follows_monitor "$state"
