#!/usr/bin/env sh

. io.sh
. shellverbose.sh

playerctl -l | while IFS= read -r player; do
    std_log "Stopping player $player."
    playerctl -p "$player" pause
done &

bspc query -N | while IFS= read -r id; do
    name="$(
        xprop -id "$id" '\n$0\n' _NET_WM_NAME 2> /dev/null \
            | tail -n +2 \
            | tail -c +2 \
            | head -c -1
    )"

    std_log "Found window with ID $id and name $name."

    case "$name" in
        *YouTube*) :;;
        *) continue;;
    esac

    std_log "Hiding window with ID $id and name $name."
    bspc node "$id" -g hidden=on
done &

wait
