#!/usr/bin/env sh
# Toggle the mute status of the default pulseaudio source.

. shellverbose.sh

. config.sh
. prefix.sh

play_audio() {
    action="$1"
    # shellcheck disable=SC2154
    fl="$(printf "%s\0" "$std_config_home/$action"* | shuf -n 1 -z)"
    [ -f "$fl" ] && play -- "$fl" 2> /dev/null
}

pactl set-source-mute "$(voldefsource)" toggle
ret="$?"

if [ "$(pactl get-source-mute "$(voldefsource)" | cut -d' ' -f2)" = "yes" ]; then
    play_audio mute
else
    play_audio unmute
fi

exit "$ret"
