#!/usr/bin/env sh

. std.sh

fzf --preview "printf '%s\n' {}
                   | awk '{for (i=2; i<NF; i++) printf \$i \" \"; print \$NF}'
                   | expandpath
                   | xargs -d '\n'
                   ls --color=always --
    " < "$(getpath -fu -- mrk)" \
    | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}' \
    | expandpath
