#!/usr/bin/env sh

. shellverbose.sh

[ "$#" -gt 1 ] && {
    printf "Less than 2 arguments are accepted.\n" >&2
    exit 1
}

[ "$#" -eq 0 ] && {
    printf "%s\n" "$HOME"
    exit 0
}

dir="$(getdirallunsafe "$1")"

if [ -d "$dir" ]; then
    printf "%s\n" "$dir"
else
    printf "No such directory.\n" >&2
    exit 1
fi
