#!/usr/bin/env sh
# Change directory of mark.

. std.sh

. io.sh

mark="$1"
[ -z "$mark" ] && exit 1
val="$2"
mrkfl="$(getpath -fu -- mrk)"

[ "$mark" != "¬" ] && {
    curval="$(grep "^$mark\s" -- "$mrkfl" | sed 's/^[^ ]*\s*\|\s*$//g')"
    [ "$curval" != "$val" ] && {
        printf "Current value: %s\nNew value    : %s\nOverwrite mark [%s]? (y/N)\n" \
                               "$curval"          "$val"              "$mark"
        equals "$(std_read_char_tty)" Y y || exit 0
    }
}

gawk -i inplace -v mrkfl="$mark" -v val="$val" \
    '$1 == mrkfl {$0 = ""; $1 = mrkfl; $2 = val}1' "$mrkfl"
