#!/usr/bin/env sh
# Select a file using fzf and open them in "$EDITOR".

. std.sh
. util.sh

main() {
    fl="$(
        find -L "${root_dir:-"."}" -type f -not -path "*/.git/*" -printf "%P\n" \
            | XENVS_PRE_QUERY="$query" xenvs -r -- \
                fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}' \
                    --preview-window 'right,60%,wrap'
    )" && [ -n "$fl" ] || exit 0
    unset query
    "$EDITOR" -- "$root_dir$fl"
}

if [ "$#" -eq 0 ]; then
    root_dir=""
else
    root_dir="$1/"
    shift 1

    if [ "$#" -eq 0 ]; then
        unset query
    else
        query="--query=$*"
    fi
fi

while :; do
    main
done
