#!/usr/bin/env sh
# Get directories or the directories of files with given codes.

. std.sh

for i; do
    loc="$(getpath -d -- "$i")" || {
        loc="$(getpath -f -- "$i")" || continue
        loc="${loc%/*}"
    }
    printf "%s\n" "$loc"
done
