[package]
name = "termctl"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
clap = { version = "4.0", features = ["derive"] }
exitfailure = "0.5.1"
fstrings = "0.2.3"
termion = "2.0.1"
