#!/usr/bin/env sh

starttsm() {
    WINEPREFIX=/games/wow-tsm wine setsid --fork -- '/games/wow-tsm/drive_c/Program Files (x86)/TradeSkillMaster Application/app/TSMApplication.exe' &
}

startrio() {
    setsid --fork -- "$(getdir prog)/RaiderIO/AppRun" &
}

startwow() {
    screen -dmS wow sh -c 'lutris lutris:rungame/world-of-warcraft'
}

startall() {
    starttsm
    startrio
    startwow
}

"/games/world-of-warcraft/drive_c/Program Files (x86)/World of Warcraft/_retail_/CurseBreaker" update &

input="$(printf "All\nTSM\nRaiderIO\nWoW" | execmenu -i -p "wowstart:")"

wait

[ -z "$input" ] && exit 0

case "$input" in
    "All"      ) startall;;
    "TSM"      ) starttsm;;
    "RaiderIO" ) startrio;;
    "WoW"      ) startwow;;
    *          ) exit 1;;
esac
