#!/usr/bin/env sh

eval "$(evalverbose)"

getchildren() {
    children="$(pgrep -P "$1")"
    [ -z "$children" ] && return
    printf "%s\n" "$children"
    printf "%s\n" "$children" | while IFS= read -r i; do
        getchildren "$i"
    done
}

for i; do
    getchildren "$1"
done | uniqs
