#!/usr/bin/env sh

eval "$(evalverbose)"

eval "$(getpath -due -- "${1}lck" lckdir 1 "getpath -du -- failed with code $? for keycode ${1}lck, exiting with code 1.")"

[ -n "$lckdir" ] || {
    printf "getpath -du -- returned empty for keycode ${1}lck, exiting with code 2.\n" >&2
    exit 1
}

exec lck "$lckdir"
