#!/usr/bin/env sh

SEP="${SEP:-"="}"
END="${END-"
"}"

IFS=

while IFS= read -r i; do
    for j; do
        from="${j%%"$SEP"*}"
        to="${j#*"$SEP"}"
        case "$i" in
            $from) 
                printf "%s%s" "$to" "$END"
                continue 2
                ;;
        esac
    done

    printf "%s%s" "$i" "$END"
done <&0
