#!/usr/bin/env sh

. evalverbose.sh

stdinfl="$(mktemp)"
[ ! -t 0 ] && cp -- /dev/stdin "$stdinfl"

unset isdmenu hasprompt
prompt=0

for i; do
    [ "$i" = "-dmenu" ] && {
        isdmenu=1
        continue
    }

    [ "$isdmenu" = 1 ] && [ "$i" = "-p" ] && {
        hasprompt=1
        continue
    }
    [ "$hasprompt" = 1 ] && {
        prompt="$i"
        break
    }
done

[ "$isdmenu" = 1 ] && {
    res="$(resmoncur)"
    exec "$@" -theme-str "
        window {
            width:  $(numsh -f min -- \
                        "$((${ROFIFIT_WIDTH_OFFSET:-0} + $(numsh -f max \
                            "$((50 + 12 * $(wc -L < "$stdinfl")))" \
                            "$((200 + 12 * ${#prompt}))"
                        )))" \
                        "$((${res%%x*} / 2))"
                    );
            height: $(numsh -f min -- \
                        "$((${ROFIFIT_HEIGHT_OFFSET:-0} + 37 + 23 * $(wc -l < "$stdinfl")))" \
                        "$((${res##*x} / 2 + 3))"
                    );
        }" < "$stdinfl"
}
exec "$@" < "$stdinfl"
