#!/usr/bin/env sh

stdinfl="$(mktemp)"
cp -- /dev/stdin "$stdinfl"

unset isdmenu hasprompt
prompt=0

for i; do
    [ "$i" = "-dmenu" ] && {
        isdmenu=1
        continue
    }

    [ "$isdmenu" = 1 ] && [ "$i" = "-p" ] && {
        hasprompt=1
        continue
    }
    [ "$hasprompt" = 1 ] && {
        prompt="$i"
        break
    }
done

[ "$isdmenu" = 1 ] && exec rofi "$@" -theme-str "window { width: $((($(max "${#prompt}" "$(wc -L < "$stdinfl")") + 2) * 16)); }" < "$stdinfl"
exec rofi "$@" < "$stdinfl"
