#!/usr/bin/env sh

. shellverbose.sh

tmp="$(mktemp)"
trap 'rm -f -- "$tmp"' EXIT INT QUIT TERM
cp -f -- /dev/stdin "$tmp"
stdl="$(wc -l < "$tmp")"

tput smcup
tput civis
clear
terml="$(tput lines)"
[ "$terml" -gt "$stdl" ] && putsn "$(((terml - stdl) / 2))"
cat -- "$tmp"
