#!/usr/bin/env sh
# xdg-open wrapper.

open() {
    if [ "$(grep -E -m 1 "^Terminal=.*" -- "$2" | sed 's/^Terminal=//')" = "true" ]; then
        exec xdg-open "$1" 
    else
        xdg-open "$1" &
    fi
}

case "$(mimetype --brief -- "$1")" in
    text/*         ) exec "$EDITOR" -- "$1";;
    application/pdf) exec zathura   -- "$1";;
esac

dtf="$(grep -m 1 "$(mimetype -- "$1" | awk '{print $2}')" "$(getfl mim)" | sed -e 's/^.*=//' -e 's/;$//')"
[ -z "$dtf" ] && exec xdg-open "$1"

lf="$(find "$(getdir lsa)" -name "$dtf" | sort | head -n 1)"
if [ -n "$lf" ]; then
    open "$1" "$lf"
else
    uf="$(find "$(getdir usa)" -name "$dtf" | sort | head -n 1)"
    [ -n "$uf" ] && open "$1" "$uf"
fi
