#!/usr/bin/env sh
# xdg-open wrapper.

open() {
    if [ "$(grep -E -m 1 "^Terminal=.*" -- "$2" | sed 's/^Terminal=//')" = "true" ]; then
        xdg-open "$1" 
    else
        xdg-open "$1" &
    fi
}

usa="$(getdir usa)" || {
    printf "[ERROR]: getdir failed, aborting.\n"
    exit 1
}
lsa="$(getdir lsa)" || {
    printf "[ERROR]: getdir failed, aborting.\n"
    exit 1
}
mim="$(getfl mim)" || {
    printf "[ERROR]: getfl failed, aborting.\n"
    exit 1
}

for i; do
    [ "$(mimetype --brief -- "$i" | cut -d/ -f-1)" = "text" ] && {
        eval "'$EDITOR' -- '$i'"
        continue
    }

    # find desktop file
    dtf="$(grep -m 1 "$(mimetype -- "$i" | awk '{print $2}')" "$mim" | sed -e 's/^.*=//' -e 's/;$//')"

    [ -n "$dtf" ] || {
        xdg-open "$i"
        continue
    }

    lf="$(find "$lsa" -name "$dtf" | sort | head -n 1)"

    [ -n "$lf" ] && {
        open "$i" "$lf"
        continue
    }

    uf="$(find "$usa" -name "$dtf" | sort | head -n 1)"

    [ -n "$uf" ] && {
        open "$i" "$uf"
        continue
    }
done
