#!/usr/bin/env sh
# xdg-open wrapper.

open() {
    if [ "$(grep -E -m 1 "^Terminal=.*" -- "$2" | sed 's/^Terminal=//')" = "true" ]; then
        exec xdg-open "$1"
    else
        xdg-open "$1" &
    fi
}

case "$(mimetype --brief -- "$1")" in
    text/*         )
        if [ -t 0 ]; then
            exec "$EDITOR" -- "$1"
        else
            exec "$TERMINAL" -e "$EDITOR" -- "$1"
        fi
        ;;
    application/pdf) exec zathura   -- "$1";;
esac

dtf="$(
    grep -m 1 "$(mimetype -- "$1" | awk '{print $2}')" "$(getfl mim)" \
        | sed -e 's/^.*=//' -e 's/;$//'
)"
[ -z "$dtf" ] && exec xdg-open "$1"

lf="$(find "${XDG_DATA_HOME:-"$HOME/.local/share"}/applications" "/usr/local/share/applications" "/usr/share/applications" -name "$dtf" | head -n 1)"
if [ -n "$lf" ]; then
    open "$1" "$lf"
else
    exec xdg-open "$1"
fi
