#!/usr/bin/env sh

printf "%s " \
    "''" \
    "'~'" \
    "'~/'" \
    "'~/XXXXXX'" \
    "'~/XXXXXX/YYYYYY'" \
    "'~XXXXXX'" \
    "'~XXXXXX/'" \
    "'/root'" \
    "'/root/XXXXXX'" \
    "'XXXXXX'" \
    "'/XXXXXX/'"
