#!/usr/bin/env sh

. shellverbose.sh

case "$1" in
    c|clean) rm -f -- main.c program;;
    *)
        if [ -f "main.cpp" ]; then
            fl="main.cpp"
        else
            fl="main.c"
        fi

        gcc "$fl" -Wall -o program && ./program "$@"
        ;;
esac
