#!/usr/bin/env sh

. shellverbose.sh

players="$(playerctl -l -i "$PLAYERCTLSELIGNORE")"
if [ "$(printf "%s\n" "$players" | wc -l)" -lt 2 ]; then
    playerctl "$@"
else
    printf "%s\n" "$players" | execmenu | xargs -d '\n' -rI PLAYER playerctl -p PLAYER "$@"
fi
