#!/usr/bin/env sh

. std.sh

until [ -f "ProjectSettings/ProjectVersion.txt" ]; do
    [ "$PWD" = "/" ] && exit 1
    cd ..
done

cmd="$1"
shift
case "$cmd" in
    astyle)
        if [ "$#" -ne 0 ]; then
            astyle --mode=cs --project=.astylerc "$@"
        else
            find Assets/Scripts -type f -iname "*.cs" -print0 \
                | xargs -r0 astyle --mode=cs --project=.astylerc
        fi
        ;;
    dotnet)
        project="${PWD##*/}"
        dotnet format "$project.csproj" "$@"
        ;;
esac
