name: analyse

on:
  push:
    branches:
      - master
    paths:
      - src/*/**
      - src/.make
      - Makefile
      - .github/**
  pull_request:
    branches:
      - master
    paths:
      - src/*/**
      - src/.make
      - Makefile
      - .github/**

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: dep
      run: |
        sudo apt -y install moreutils shellcheck pylint clang-tools libbsd-dev
        git submodule update --init --recursive
    - name: analyse
      run: |
        make analyse
