name: analyse

on:
  push:
    branches:
      - '**'
    paths:
      - src/*/**
      - src/.make
      - Makefile
      - .github/**
  pull_request:
    branches:
      - '**'
    paths:
      - src/*/**
      - src/.make
      - Makefile
      - .github/**

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: dep
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get -y install moreutils shellcheck pylint clang-tools cppcheck libbsd-dev
        git submodule update --init --recursive
      env:
        SHELL_VERBOSE: 1
    - name: analyse
      run: |
        make analyse
      env:
        SHELL_VERBOSE: 1
