name: build

on:
  push:
    branches:
      - '**'
    paths:
      - src/**
      - Makefile
      - .github/**
      - test/**
  pull_request:
    branches:
      - '**'
    paths:
      - src/**
      - Makefile
      - .github/**
      - test/**

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: dep
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get -y install libmagic-dev moreutils libbsd-dev cargo libncurses5-dev libncursesw5-dev ncurses-bin
        git submodule update --init --recursive
      env:
        SHELL_VERBOSE: 1
    - name: build
      run: |
        ./.make install
        ./.make uninstall
      env:
        SHELL_VERBOSE: 1
    - name: sudo-build
      run: |
        sudo ./.make install
      env:
        SHELL_VERBOSE: 1
    - name: test
      run: |
        ./.make test
      env:
        SHELL_VERBOSE: 1
    - name: sudo-test
      run: |
        sudo ./.make test
      env:
        SHELL_VERBOSE: 1
