name: Build

on:
  push:
    branches:
      - '**'
    paths:
      - .make
      - src/**
      - Makefile
      - .github/**
      - test/**
  pull_request:
    branches:
      - '**'
    paths:
      - .make
      - src/**
      - Makefile
      - .github/**
      - test/**

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install workflow dependencies
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get -y install libmagic-dev moreutils libbsd-dev cargo libncurses5-dev libncursesw5-dev ncurses-bin libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev
        git submodule update --init --recursive
      env:
        SHELL_VERBOSE: 1
    - name: Compile and install executables
      run: |
        ./.make install
        ./.make uninstall
      env:
        SHELL_VERBOSE: 1
    - name: Compile and install executables as root
      run: |
        sudo ./.make install
      env:
        SHELL_VERBOSE: 1
    - name: Test installed executables
      run: |
        ./.make test
      env:
        SHELL_VERBOSE: 1
    - name: Test installed executables as root
      run: |
        sudo ./.make test
      env:
        SHELL_VERBOSE: 1
