name: build

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - Makefile
      - .github/**
  pull_request:
    branches:
      - master
    paths:
      - src/**
      - Makefile
      - .github/**

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: dep
      run: |
        sudo apt -y install libmagic-dev moreutils libbsd-dev
        curl https://sh.rustup.rs -sSf | sudo sh -s -- -y
        source "$HOME/.cargo/env"
        sudo rustup update
        git submodule update --init --recursive
    - name: build
      run: |
        make install
        make uninstall
    - name: sudo-build
      run: |
        sudo make install
    - name: test
      run: |
        make test
    - name: sudo-test
      run: |
        sudo make test
