name: build

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - Makefile
      - .github/**
  pull_request:
    branches:
      - master
    paths:
      - src/**
      - Makefile
      - .github/**

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: dep
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get -y install libmagic-dev moreutils libbsd-dev cargo libncurses5-dev libncursesw5-dev
        git submodule update --init --recursive
    - name: build
      run: |
        make install
        make uninstall
    - name: sudo-build
      run: |
        sudo make install
    - name: test
      run: |
        make test
    - name: sudo-test
      run: |
        sudo make test
