name: make

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: dep
      run: |
        sudo apt -y install libmagic-dev moreutils
    - name: build
      run: |
        make install
        make uninstall
    - name: sudo-build
      run: |
        sudo make install
    - name: test
      run: |
        make test
    - name: sudo-test
      run: |
        sudo make test
