name: Check Spelling

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  spell:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt-get -y install codespell
    - name: Check for Spelling Mistakes
      run: |
        ./.make spell
      env:
        SHELL_VERBOSE: 1
