name: spell

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: dep
      run: |
        sudo apt-get -y install codespell
    - name: spell
      run: |
        ./.make spell
      env:
        SHELL_VERBOSE: 1
