name: stats

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: stats
      run: |
        cd src/ || exit 1
        ./.make stats
      env:
        SHELL_VERBOSE: 1
