name: Statistics

on:
  push:
    branches:
      - '**'

jobs:
  stats:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Print statistics
      run: |
        ./.make stats
